export const MOB_IDS = {
  FERROUS_MITE: 'ferrous_mite',
  SCORIA_SAPPER: 'scoria_sapper',
  ORBITAL_STINGER: 'orbital_stinger',
  PRISMATIC_LANCER: 'prismatic_lancer',
  SENTINEL_NODULE: 'sentinel_nodule',
  PLASMA_CRUSHER: 'plasma_crusher',
  ARC_WARDEN: 'arc_warden',
  VECTOR_SPECTER: 'vector_specter',
  SHRAPNEL_HYDRA: 'shrapnel_hydra',
  APEX_PREDATOR: 'apex_predator'
};

export const MOB_BEHAVIOR_IDS = {
  RUSHER: 'rusher',
  BOMBER: 'bomber',
  SKIRMISHER: 'skirmisher',
  SNIPER: 'sniper',
  SENTRY: 'sentry',
  MELEE_CHASE: 'rusher',
  RANGED_KITE: 'skirmisher'
};

function color(r, g, b) { return { r, g, b }; }

export const MOB_DEFS = {
  [MOB_IDS.FERROUS_MITE]: {
    id: MOB_IDS.FERROUS_MITE,
    typeId: 1,
    name: 'Mite ferreuse',
    shortName: 'Mite',
    role: 'Rusher / engage',
    variantFamily: 'Basique',
    radius: 13,
    color: color(218, 165, 32),
    maxHp: 82,
    moveSpeed: 168,
    aggroRange: 420,
    leashRange: 620,
    attackRange: 34,
    preferredRange: 34,
    retreatRange: 0,
    attackCooldownMs: 720,
    attackDamage: 10,
    xpReward: 12,
    contactPush: 150,
    dropResource: 'scrap',
    dropMin: 1,
    dropMax: 2,
    sectorMinLevel: 1,
    spawnWeight: 8,
    behaviorId: MOB_BEHAVIOR_IDS.RUSHER,
    threat: 1,
    eliteScale: 1.18,
    abilities: ['Charge magnétique', 'Salve marquante', 'Essaim mineur'],
    kit: 'Charge, marque, ralentit/ground sur salves avancées.',
    onHit: [{ effectId: 'mark', duration: 4, markKey: 'mite', stacks: 1, maxStacks: 5 }],
    abilityProfile: 'mite'
  },
  [MOB_IDS.SCORIA_SAPPER]: {
    id: MOB_IDS.SCORIA_SAPPER,
    typeId: 2,
    name: 'Sapeur de scories',
    shortName: 'Sapeur',
    role: 'Bomber / mines',
    variantFamily: 'Explosif',
    radius: 15,
    color: color(255, 140, 0),
    maxHp: 132,
    moveSpeed: 104,
    aggroRange: 500,
    leashRange: 680,
    attackRange: 360,
    preferredRange: 290,
    retreatRange: 120,
    attackCooldownMs: 1320,
    attackDamage: 17,
    xpReward: 20,
    contactPush: 90,
    projectileTint: color(255, 150, 70),
    projectileRadius: 7,
    projectileSpeed: 285,
    projectileRange: 460,
    projectileSplashRadius: 74,
    dropResource: 'ore',
    dropMin: 1,
    dropMax: 2,
    sectorMinLevel: 2,
    spawnWeight: 5,
    behaviorId: MOB_BEHAVIOR_IDS.BOMBER,
    threat: 2,
    eliteScale: 1.2,
    abilities: ['Mines de scories', 'Bombe commotion', 'Tir incendiaire'],
    kit: 'Projectiles splash, burn, heal cut, mines de contrôle.',
    onHit: [{ effectId: 'burn', duration: 3.2, periodicDamage: 3.5, tickEvery: 1 }, { effectId: 'heal_cut', duration: 2.4, value: 0.28 }],
    abilityProfile: 'scoria'
  },
  [MOB_IDS.ORBITAL_STINGER]: {
    id: MOB_IDS.ORBITAL_STINGER,
    typeId: 3,
    name: 'Dard orbital',
    shortName: 'Stinger',
    role: 'Skirmisher / blind',
    variantFamily: 'Assassin',
    radius: 16,
    color: color(0, 191, 255),
    maxHp: 108,
    moveSpeed: 158,
    aggroRange: 560,
    leashRange: 760,
    attackRange: 390,
    preferredRange: 320,
    retreatRange: 150,
    attackCooldownMs: 990,
    attackDamage: 14,
    xpReward: 18,
    contactPush: 80,
    projectileTint: color(140, 220, 255),
    projectileRadius: 5,
    projectileSpeed: 420,
    projectileRange: 520,
    projectileSplashRadius: 0,
    dropResource: 'crystal',
    dropMin: 1,
    dropMax: 2,
    sectorMinLevel: 3,
    spawnWeight: 5,
    behaviorId: MOB_BEHAVIOR_IDS.SKIRMISHER,
    threat: 2,
    eliteScale: 1.16,
    abilities: ['Cloak bref', 'Dard aveuglant', 'Blink latéral'],
    kit: 'Se repositionne, prépare un tir blind + damage amp.',
    onHit: [{ effectId: 'blind', duration: 1.25 }, { effectId: 'damage_amp', duration: 2.6, value: 0.16 }],
    abilityProfile: 'stinger'
  },
  [MOB_IDS.PRISMATIC_LANCER]: {
    id: MOB_IDS.PRISMATIC_LANCER,
    typeId: 4,
    name: 'Lancier prismatique',
    shortName: 'Lancier',
    role: 'Sniper / burst',
    variantFamily: 'Longue portée',
    radius: 17,
    color: color(255, 105, 180),
    maxHp: 122,
    moveSpeed: 112,
    aggroRange: 780,
    leashRange: 950,
    attackRange: 620,
    preferredRange: 560,
    retreatRange: 250,
    attackCooldownMs: 1550,
    attackDamage: 27,
    xpReward: 28,
    contactPush: 70,
    projectileTint: color(255, 125, 235),
    projectileRadius: 4.5,
    projectileSpeed: 610,
    projectileRange: 860,
    projectileSplashRadius: 0,
    dropResource: 'crystal',
    dropMin: 2,
    dropMax: 3,
    sectorMinLevel: 5,
    spawnWeight: 3,
    behaviorId: MOB_BEHAVIOR_IDS.SNIPER,
    threat: 3,
    eliteScale: 1.18,
    abilities: ['Lance prismatique', 'Null field', 'Exécution révélée'],
    kit: 'Très longue portée, reveal, sleep/amp synergies, finisher.',
    onHit: [{ effectId: 'reveal', duration: 3.2 }, { effectId: 'damage_amp', duration: 2.2, value: 0.18 }],
    abilityProfile: 'lancer'
  },
  [MOB_IDS.SENTINEL_NODULE]: {
    id: MOB_IDS.SENTINEL_NODULE,
    typeId: 5,
    name: 'Nodule sentinelle',
    shortName: 'Nodule',
    role: 'Sentry / lockfield',
    variantFamily: 'Défensif',
    radius: 17,
    color: color(147, 112, 219),
    maxHp: 188,
    moveSpeed: 78,
    aggroRange: 570,
    leashRange: 720,
    attackRange: 420,
    preferredRange: 350,
    retreatRange: 80,
    attackCooldownMs: 930,
    attackDamage: 15,
    xpReward: 26,
    contactPush: 100,
    projectileTint: color(170, 140, 255),
    projectileRadius: 5,
    projectileSpeed: 350,
    projectileRange: 600,
    projectileSplashRadius: 28,
    dropResource: 'ore',
    dropMin: 2,
    dropMax: 3,
    sectorMinLevel: 6,
    spawnWeight: 3,
    behaviorId: MOB_BEHAVIOR_IDS.SENTRY,
    threat: 3,
    eliteScale: 1.2,
    abilities: ['Bastion', 'Lockfield', 'Grounded shot'],
    kit: 'Shield périodique, lockfield, grounded/knockback.',
    onHit: [{ effectId: 'grounded', duration: 1.1 }, { effectId: 'knockback', duration: 0.15, value: 30 }],
    abilityProfile: 'nodule'
  },
  [MOB_IDS.PLASMA_CRUSHER]: {
    id: MOB_IDS.PLASMA_CRUSHER,
    typeId: 6,
    name: 'Broyeur plasma',
    shortName: 'Broyeur',
    role: 'Bruiser / melee',
    variantFamily: 'Lourd',
    radius: 18,
    color: color(255, 69, 0),
    maxHp: 178,
    moveSpeed: 142,
    aggroRange: 480,
    leashRange: 680,
    attackRange: 52,
    preferredRange: 42,
    retreatRange: 0,
    attackCooldownMs: 1020,
    attackDamage: 26,
    xpReward: 30,
    contactPush: 190,
    dropResource: 'scrap',
    dropMin: 2,
    dropMax: 4,
    sectorMinLevel: 7,
    spawnWeight: 3,
    behaviorId: MOB_BEHAVIOR_IDS.RUSHER,
    threat: 4,
    eliteScale: 1.2,
    abilities: ['EMP pulse', 'Plasma crush', 'Gravitic sweep'],
    kit: 'Mêlée lourde, stun/grounded, dash, zone de pression.',
    onHit: [{ effectId: 'stun', duration: 0.35 }, { effectId: 'grounded', duration: 0.9 }],
    abilityProfile: 'crusher'
  },
  [MOB_IDS.ARC_WARDEN]: {
    id: MOB_IDS.ARC_WARDEN,
    typeId: 7,
    name: 'Gardien arc',
    shortName: 'Warden',
    role: 'Sentry / chain',
    variantFamily: 'Électrique',
    radius: 19,
    color: color(100, 149, 237),
    maxHp: 172,
    moveSpeed: 96,
    aggroRange: 650,
    leashRange: 820,
    attackRange: 470,
    preferredRange: 390,
    retreatRange: 130,
    attackCooldownMs: 1180,
    attackDamage: 20,
    xpReward: 32,
    contactPush: 95,
    projectileTint: color(140, 190, 255),
    projectileRadius: 5,
    projectileSpeed: 430,
    projectileRange: 650,
    projectileSplashRadius: 38,
    dropResource: 'crystal',
    dropMin: 2,
    dropMax: 3,
    sectorMinLevel: 8,
    spawnWeight: 2,
    behaviorId: MOB_BEHAVIOR_IDS.SENTRY,
    threat: 4,
    eliteScale: 1.18,
    abilities: ['Arc burst', 'Concussion', 'Bastion lockfield'],
    kit: 'Salves électriques, stun/grounded, dégâts contre cibles contrôlées.',
    onHit: [{ effectId: 'stun', duration: 0.28 }, { effectId: 'grounded', duration: 0.7 }],
    abilityProfile: 'warden'
  },
  [MOB_IDS.VECTOR_SPECTER]: {
    id: MOB_IDS.VECTOR_SPECTER,
    typeId: 8,
    name: 'Spectre vectoriel',
    shortName: 'Spectre',
    role: 'Skirmisher / psychic',
    variantFamily: 'Furtif',
    radius: 16,
    color: color(186, 85, 211),
    maxHp: 135,
    moveSpeed: 172,
    aggroRange: 660,
    leashRange: 860,
    attackRange: 390,
    preferredRange: 310,
    retreatRange: 140,
    attackCooldownMs: 1020,
    attackDamage: 19,
    xpReward: 35,
    contactPush: 80,
    projectileTint: color(210, 120, 255),
    projectileRadius: 5,
    projectileSpeed: 480,
    projectileRange: 620,
    projectileSplashRadius: 0,
    dropResource: 'voidGlass',
    dropMin: 1,
    dropMax: 2,
    sectorMinLevel: 9,
    spawnWeight: 2,
    behaviorId: MOB_BEHAVIOR_IDS.SKIRMISHER,
    threat: 4,
    eliteScale: 1.18,
    abilities: ['Vector blink', 'Dread veil', 'Charm/Fear rupture'],
    kit: 'Furtif, peur/charme, amp, repositionnement.',
    onHit: [{ effectId: 'fear', duration: 0.65 }, { effectId: 'charm', duration: 0.45 }],
    abilityProfile: 'specter'
  },
  [MOB_IDS.SHRAPNEL_HYDRA]: {
    id: MOB_IDS.SHRAPNEL_HYDRA,
    typeId: 9,
    name: 'Hydre de limaille',
    shortName: 'Hydre',
    role: 'Bomber / poison',
    variantFamily: 'Toxique',
    radius: 19,
    color: color(50, 205, 50),
    maxHp: 205,
    moveSpeed: 104,
    aggroRange: 620,
    leashRange: 820,
    attackRange: 430,
    preferredRange: 340,
    retreatRange: 100,
    attackCooldownMs: 1120,
    attackDamage: 18,
    xpReward: 42,
    contactPush: 90,
    projectileTint: color(110, 255, 140),
    projectileRadius: 6,
    projectileSpeed: 330,
    projectileRange: 620,
    projectileSplashRadius: 84,
    dropResource: 'bioFiber',
    dropMin: 2,
    dropMax: 4,
    sectorMinLevel: 11,
    spawnWeight: 2,
    behaviorId: MOB_BEHAVIOR_IDS.BOMBER,
    threat: 5,
    eliteScale: 1.22,
    abilities: ['Corrosive mire', 'Brood hive', 'Poison globe'],
    kit: 'Poison traversant, pull/fear, se renforce contre cibles empoisonnées.',
    onHit: [{ effectId: 'poison', duration: 4, periodicDamage: 5.5, tickEvery: 1 }, { effectId: 'slow', duration: 1.3, value: 0.22 }],
    abilityProfile: 'hydra'
  },
  [MOB_IDS.APEX_PREDATOR]: {
    id: MOB_IDS.APEX_PREDATOR,
    typeId: 10,
    name: 'Prédateur apex',
    shortName: 'Apex',
    role: 'Boss hunter',
    variantFamily: 'Apex',
    radius: 20,
    color: color(220, 20, 60),
    maxHp: 260,
    moveSpeed: 155,
    aggroRange: 780,
    leashRange: 980,
    attackRange: 330,
    preferredRange: 220,
    retreatRange: 0,
    attackCooldownMs: 850,
    attackDamage: 28,
    xpReward: 60,
    contactPush: 210,
    projectileTint: color(255, 90, 110),
    projectileRadius: 6,
    projectileSpeed: 500,
    projectileRange: 720,
    projectileSplashRadius: 26,
    dropResource: 'voidGlass',
    dropMin: 3,
    dropMax: 5,
    sectorMinLevel: 13,
    spawnWeight: 1,
    behaviorId: MOB_BEHAVIOR_IDS.RUSHER,
    threat: 6,
    eliteScale: 1.26,
    abilities: ['Hunt circle', 'Dread veil', 'Execute bleed'],
    kit: 'Prédateur mobile, bleed/reveal, fear, exécution sur cibles basses.',
    onHit: [{ effectId: 'bleed', duration: 3.5, periodicDamage: 6, tickEvery: 1 }, { effectId: 'reveal', duration: 3.2 }],
    abilityProfile: 'apex'
  }
};

export function getMobDef(id) {
  return MOB_DEFS[id] ?? null;
}

export function listMobDefs() {
  return Object.values(MOB_DEFS);
}
