export const ENGINE_TONE_PROFILES = {
  vanguard: {
    id: 'vanguard',
    name: 'Vanguard',
    oscType: 'triangle',
    subType: 'sine',
    noiseColor: 'warm',
    baseFreq: 42,
    thrustFreq: 36,
    subFreq: 0.50,
    filterBase: 145,
    filterThrust: 360,
    q: 0.55,
    oscGain: 0.38,
    subGain: 0.24,
    noiseGain: 0.080,
    movementGain: 0.038,
    idleGain: 0.0038,
    attack: 0.18,
    release: 0.35,
    vibratoDepth: 1.8,
    vibratoRate: 0.55
  },
  sigil: {
    id: 'sigil',
    name: 'Sigil',
    oscType: 'sine',
    subType: 'triangle',
    noiseColor: 'soft',
    baseFreq: 58,
    thrustFreq: 28,
    subFreq: 0.50,
    filterBase: 210,
    filterThrust: 460,
    q: 0.70,
    oscGain: 0.27,
    subGain: 0.20,
    noiseGain: 0.055,
    movementGain: 0.032,
    idleGain: 0.0032,
    attack: 0.22,
    release: 0.42,
    vibratoDepth: 3.4,
    vibratoRate: 0.42
  },
  bulwark: {
    id: 'bulwark',
    name: 'Bulwark',
    oscType: 'triangle',
    subType: 'sine',
    noiseColor: 'heavy',
    baseFreq: 32,
    thrustFreq: 26,
    subFreq: 0.50,
    filterBase: 120,
    filterThrust: 300,
    q: 0.45,
    oscGain: 0.38,
    subGain: 0.30,
    noiseGain: 0.080,
    movementGain: 0.041,
    idleGain: 0.0042,
    attack: 0.25,
    release: 0.50,
    vibratoDepth: 0.9,
    vibratoRate: 0.34
  },
  default: {
    id: 'default',
    name: 'Standard',
    oscType: 'triangle',
    subType: 'sine',
    noiseColor: 'soft',
    baseFreq: 44,
    thrustFreq: 32,
    subFreq: 0.50,
    filterBase: 150,
    filterThrust: 340,
    q: 0.55,
    oscGain: 0.30,
    subGain: 0.20,
    noiseGain: 0.055,
    movementGain: 0.034,
    idleGain: 0.0034,
    attack: 0.20,
    release: 0.42,
    vibratoDepth: 1.2,
    vibratoRate: 0.45
  }
};

export function getEngineToneProfile(frameId) {
  const id = String(frameId || '').toLowerCase();
  return ENGINE_TONE_PROFILES[id] || ENGINE_TONE_PROFILES.default;
}
