// Ressources v83 : liste réduite, noms physiques crédibles, anciens ids conservés en compatibilité.
export const ACTIVE_RESOURCE_KEYS_ORDER = [
  "scrap",
  "ironOre",
  "copper",
  "nickelOre",
  "titaniumOre",
  "aluminiumOre",
  "cobaltOre",
  "silicon",
  "quartz",
  "graphite",
  "lithiumOre",
  "boronOre",
  "berylliumOre",
  "rareEarthOre",
  "waterIce",
  "hydrogenIce",
  "methaneIce",
  "ammoniaIce",
  "hydrocarbons",
  "sulfur",
  "uraniumOre",
  "thoriumOre",
  "unstableIsotopes",
  "leadOre",
  "biomass",
  "chitin",
  "organicLipids",
  "enzymes",
  "proteinFibers",
  "spores",
  "containedAntimatter",
  "strangeMatter",
  "unknownTechFragment",
  "ancientSuperconductor",
  "precursorNanomaterial",
  "ironIngot",
  "copperIngot",
  "aluminiumIngot",
  "titaniumPlate",
  "steelPlate",
  "copperWire",
  "siliconWafer",
  "microTransistor",
  "printedCircuit",
  "controlCircuit",
  "microprocessor",
  "opticalGlass",
  "laserLens",
  "lithiumBattery",
  "fuelCell",
  "refinedFuel",
  "biofuel",
  "propellant",
  "turbine",
  "industrialPump",
  "electricMotor",
  "servomotor",
  "fuelInjector",
  "fuelRod",
  "thermalCeramic",
  "carbonFiber",
  "compositeArmor",
  "basicSciencePack",
  "automationSciencePack",
  "industrialSciencePack",
  "energySciencePack",
  "biologySciencePack",
  "combatSciencePack",
  "advancedSciencePack",
  "anomalySciencePack",
  "logisticDroneBasic"
];
export const LEGACY_RESOURCE_KEYS_ORDER = [
  "ice",
  "uranite",
  "plasmaGel",
  "crystal",
  "bioFiber",
  "darkMatter",
  "nanoDust",
  "alloy",
  "circuit",
  "core",
  "flux",
  "antimatter",
  "relic",
  "ironVein",
  "nickelShard",
  "vanadiumGlass",
  "heliumIce",
  "sulfurStone",
  "carbonMesh",
  "quartzBloom",
  "lithiumSalt",
  "palladiumDust",
  "neodymCluster",
  "osmiumSpine",
  "iridiumPearl",
  "xenonPearl",
  "voidAmber",
  "phaseQuartz",
  "echoResin",
  "stellarAsh",
  "gravitonFilament",
  "chronoShard",
  "prismTear",
  "singularitySeed",
  "aetherFoam",
  "nullGlass",
  "basaltChunk",
  "manganeseNodule",
  "boronFlake",
  "phosphorite",
  "sodiumClathrate",
  "argonIce",
  "ceresClay",
  "grapheneVeil",
  "tungstenOre",
  "rutileShard",
  "galliumBloom",
  "seleniumThread",
  "hafniumPlate",
  "rutheniumDust",
  "telluricGlass",
  "mercuryIce",
  "cesiumSalt",
  "lanthanumKnot",
  "yttriumPrism",
  "zirconCore",
  "quasarPollen",
  "eventidePearl",
  "vacuumLotus",
  "entropySpore",
  "lumenMoss",
  "magnetarSkin"
];
export const RESOURCE_KEYS_ORDER = [...ACTIVE_RESOURCE_KEYS_ORDER, ...LEGACY_RESOURCE_KEYS_ORDER];
export const RESOURCE_DEFS = {
  "scrap": {
    "name": "Ferraille",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#b8bdc4",
    "rarity": 1,
    "baseWeight": 1.0,
    "spawnTier": 1,
    "shapeClass": "Junk",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": true,
    "id": "Scrap"
  },
  "ironOre": {
    "name": "Minerai de fer",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#9c8f86",
    "rarity": 1,
    "baseWeight": 1.45,
    "spawnTier": 1,
    "shapeClass": "Rock",
    "hardnessMultiplier": 0.96,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": true,
    "id": "IronOre"
  },
  "copper": {
    "name": "Cuivre",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#cd853f",
    "rarity": 1,
    "baseWeight": 1.25,
    "spawnTier": 1,
    "shapeClass": "Rock",
    "hardnessMultiplier": 0.92,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": true,
    "id": "Copper"
  },
  "nickelOre": {
    "name": "Minerai de nickel",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#d8d8c8",
    "rarity": 2,
    "baseWeight": 1.0,
    "spawnTier": 2,
    "shapeClass": "Rock",
    "hardnessMultiplier": 1.03,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": true,
    "id": "NickelOre"
  },
  "titaniumOre": {
    "name": "Minerai de titane",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#b7c7d9",
    "rarity": 3,
    "baseWeight": 0.72,
    "spawnTier": 4,
    "shapeClass": "Rock",
    "hardnessMultiplier": 1.13,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "TitaniumOre"
  },
  "aluminiumOre": {
    "name": "Bauxite",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#c28b65",
    "rarity": 1,
    "baseWeight": 1.05,
    "spawnTier": 1,
    "shapeClass": "Rock",
    "hardnessMultiplier": 0.95,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "AluminiumOre"
  },
  "cobaltOre": {
    "name": "Minerai de cobalt",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#4169e1",
    "rarity": 2,
    "baseWeight": 0.86,
    "spawnTier": 2,
    "shapeClass": "Rock",
    "hardnessMultiplier": 1.05,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": true,
    "id": "CobaltOre"
  },
  "silicon": {
    "name": "Silicium",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#d3d3d3",
    "rarity": 1,
    "baseWeight": 1.15,
    "spawnTier": 1,
    "shapeClass": "Rock",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": true,
    "id": "Silicon"
  },
  "quartz": {
    "name": "Quartz",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#e7d7ff",
    "rarity": 2,
    "baseWeight": 1.05,
    "spawnTier": 2,
    "shapeClass": "Crystal",
    "hardnessMultiplier": 1.08,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Quartz"
  },
  "graphite": {
    "name": "Graphite",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#4d4d4d",
    "rarity": 1,
    "baseWeight": 0.98,
    "spawnTier": 1,
    "shapeClass": "Rock",
    "hardnessMultiplier": 0.9,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": true,
    "id": "Graphite"
  },
  "lithiumOre": {
    "name": "Minerai de lithium",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#ffb6c1",
    "rarity": 2,
    "baseWeight": 0.92,
    "spawnTier": 2,
    "shapeClass": "Dust",
    "hardnessMultiplier": 0.9,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "LithiumOre"
  },
  "boronOre": {
    "name": "Minerai de bore",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#d7c39a",
    "rarity": 2,
    "baseWeight": 0.8,
    "spawnTier": 2,
    "shapeClass": "Dust",
    "hardnessMultiplier": 1.02,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "BoronOre"
  },
  "berylliumOre": {
    "name": "Minerai de béryllium",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#98e0c6",
    "rarity": 3,
    "baseWeight": 0.58,
    "spawnTier": 4,
    "shapeClass": "Rock",
    "hardnessMultiplier": 1.12,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "BerylliumOre"
  },
  "rareEarthOre": {
    "name": "Terres rares",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#48d1cc",
    "rarity": 4,
    "baseWeight": 0.5,
    "spawnTier": 5,
    "shapeClass": "Crystal",
    "hardnessMultiplier": 1.12,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "RareearthOre"
  },
  "waterIce": {
    "name": "Glace d'eau",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#add8e6",
    "rarity": 1,
    "baseWeight": 1.2,
    "spawnTier": 1,
    "shapeClass": "Ice",
    "hardnessMultiplier": 0.82,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": true,
    "id": "Waterice"
  },
  "hydrogenIce": {
    "name": "Hydrogène solide",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#e9fbff",
    "rarity": 2,
    "baseWeight": 0.86,
    "spawnTier": 2,
    "shapeClass": "Ice",
    "hardnessMultiplier": 0.8,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Hydrogenice"
  },
  "methaneIce": {
    "name": "Méthane solide",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#bcecff",
    "rarity": 2,
    "baseWeight": 0.9,
    "spawnTier": 2,
    "shapeClass": "Ice",
    "hardnessMultiplier": 0.82,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Methaneice"
  },
  "ammoniaIce": {
    "name": "Ammoniac gelé",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#d1f0ff",
    "rarity": 2,
    "baseWeight": 0.82,
    "spawnTier": 2,
    "shapeClass": "Ice",
    "hardnessMultiplier": 0.84,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Ammoniaice"
  },
  "hydrocarbons": {
    "name": "Hydrocarbures",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#5c4635",
    "rarity": 2,
    "baseWeight": 0.9,
    "spawnTier": 3,
    "shapeClass": "Dust",
    "hardnessMultiplier": 0.9,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Hydrocarbons"
  },
  "sulfur": {
    "name": "Soufre",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#ffe44d",
    "rarity": 1,
    "baseWeight": 1.0,
    "spawnTier": 1,
    "shapeClass": "Rock",
    "hardnessMultiplier": 0.9,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": true,
    "id": "Sulfur"
  },
  "uraniumOre": {
    "name": "Minerai d’uranium",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#9dff38",
    "rarity": 4,
    "baseWeight": 0.55,
    "spawnTier": 6,
    "shapeClass": "Rock",
    "hardnessMultiplier": 1.14,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "UraniumOre"
  },
  "thoriumOre": {
    "name": "Minerai de thorium",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#7ef0b3",
    "rarity": 4,
    "baseWeight": 0.5,
    "spawnTier": 6,
    "shapeClass": "Rock",
    "hardnessMultiplier": 1.16,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "ThoriumOre"
  },
  "unstableIsotopes": {
    "name": "Isotopes instables",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#c9ff65",
    "rarity": 5,
    "baseWeight": 0.32,
    "spawnTier": 8,
    "shapeClass": "Exotic",
    "hardnessMultiplier": 1.2,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Unstableisotopes"
  },
  "leadOre": {
    "name": "Minerai de plomb",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#7c8491",
    "rarity": 2,
    "baseWeight": 0.72,
    "spawnTier": 3,
    "shapeClass": "Rock",
    "hardnessMultiplier": 1.07,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "LeadOre"
  },
  "biomass": {
    "name": "Biomasse",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#80d060",
    "rarity": 1,
    "baseWeight": 1.3,
    "spawnTier": 1,
    "shapeClass": "Biomass",
    "hardnessMultiplier": 0.8,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": true,
    "id": "Biomass"
  },
  "chitin": {
    "name": "Chitine",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#d8c596",
    "rarity": 2,
    "baseWeight": 0.9,
    "spawnTier": 2,
    "shapeClass": "Biomass",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": true,
    "id": "Chitin"
  },
  "organicLipids": {
    "name": "Lipides organiques",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#b6d46a",
    "rarity": 2,
    "baseWeight": 0.88,
    "spawnTier": 2,
    "shapeClass": "Biomass",
    "hardnessMultiplier": 0.85,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": true,
    "id": "Organiclipids"
  },
  "enzymes": {
    "name": "Enzymes",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#65d9a0",
    "rarity": 3,
    "baseWeight": 0.62,
    "spawnTier": 3,
    "shapeClass": "Biomass",
    "hardnessMultiplier": 0.82,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": true,
    "id": "Enzymes"
  },
  "proteinFibers": {
    "name": "Fibres protéiques",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#a0e0b6",
    "rarity": 2,
    "baseWeight": 0.9,
    "spawnTier": 2,
    "shapeClass": "Biomass",
    "hardnessMultiplier": 0.88,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": true,
    "id": "Proteinfibers"
  },
  "spores": {
    "name": "Spores",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#b0f080",
    "rarity": 2,
    "baseWeight": 0.92,
    "spawnTier": 2,
    "shapeClass": "Biomass",
    "hardnessMultiplier": 0.78,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": true,
    "id": "Spores"
  },
  "containedAntimatter": {
    "name": "Antimatière confinée",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#f5f5f5",
    "rarity": 6,
    "baseWeight": 0.14,
    "spawnTier": 10,
    "shapeClass": "Exotic",
    "hardnessMultiplier": 1.26,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Containedantimatter"
  },
  "strangeMatter": {
    "name": "Matière étrange",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#b58cff",
    "rarity": 7,
    "baseWeight": 0.08,
    "spawnTier": 12,
    "shapeClass": "Exotic",
    "hardnessMultiplier": 1.4,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Strangematter"
  },
  "unknownTechFragment": {
    "name": "Fragment de technologie inconnue",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#c7a0ff",
    "rarity": 5,
    "baseWeight": 0.24,
    "spawnTier": 9,
    "shapeClass": "Exotic",
    "hardnessMultiplier": 1.16,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Unknowntechfragment"
  },
  "ancientSuperconductor": {
    "name": "Alliage supraconducteur ancien",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#aeefff",
    "rarity": 5,
    "baseWeight": 0.22,
    "spawnTier": 9,
    "shapeClass": "Exotic",
    "hardnessMultiplier": 1.18,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Ancientsuperconductor"
  },
  "precursorNanomaterial": {
    "name": "Nanomatériau précurseur",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#e0e0ff",
    "rarity": 6,
    "baseWeight": 0.16,
    "spawnTier": 10,
    "shapeClass": "Exotic",
    "hardnessMultiplier": 1.22,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Precursornanomaterial"
  },
  "basicSciencePack": {
    "name": "Science de base",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#7edcff",
    "rarity": 1,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Science",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "BasicSciencePack"
  },
  "automationSciencePack": {
    "name": "Science automatisation",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#c5a6ff",
    "rarity": 2,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Science",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "AutomationSciencePack"
  },
  "industrialSciencePack": {
    "name": "Science industrielle",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#ffb866",
    "rarity": 2,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Science",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "IndustrialSciencePack"
  },
  "energySciencePack": {
    "name": "Science énergétique",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#ffe66d",
    "rarity": 2,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Science",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "EnergySciencePack"
  },
  "biologySciencePack": {
    "name": "Science biologique",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#84e080",
    "rarity": 3,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Science",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "BiologySciencePack"
  },
  "combatSciencePack": {
    "name": "Science défense",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#ff8f8f",
    "rarity": 3,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Science",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "CombatSciencePack"
  },
  "advancedSciencePack": {
    "name": "Science avancée",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#f0f4ff",
    "rarity": 4,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Science",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "AdvancedSciencePack"
  },
  "anomalySciencePack": {
    "name": "Science anomalie",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#b58cff",
    "rarity": 5,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Science",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "AnomalySciencePack"
  },
  "ironIngot": {
    "name": "Lingot de fer",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#b0aaa4",
    "rarity": 1,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Component",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Ironingot"
  },
  "copperIngot": {
    "name": "Lingot de cuivre",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#d1844f",
    "rarity": 1,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Component",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Copperingot"
  },
  "aluminiumIngot": {
    "name": "Lingot d’aluminium",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#c5ccd2",
    "rarity": 1,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Component",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Aluminiumingot"
  },
  "titaniumPlate": {
    "name": "Plaque de titane",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#d9e4f6",
    "rarity": 2,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Component",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Titaniumplate"
  },
  "steelPlate": {
    "name": "Plaque d’acier",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#aab0b8",
    "rarity": 2,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Component",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Steelplate"
  },
  "copperWire": {
    "name": "Fil de cuivre",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#d58b58",
    "rarity": 2,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Component",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Copperwire"
  },
  "siliconWafer": {
    "name": "Wafer de silicium",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#cfd4da",
    "rarity": 2,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Component",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Siliconwafer"
  },
  "microTransistor": {
    "name": "Microtransistor",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#5ee37d",
    "rarity": 3,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Component",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Microtransistor"
  },
  "printedCircuit": {
    "name": "Circuit imprimé",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#00cc66",
    "rarity": 3,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Component",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Printedcircuit"
  },
  "controlCircuit": {
    "name": "Circuit de contrôle",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#33ee88",
    "rarity": 4,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Component",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Controlcircuit"
  },
  "microprocessor": {
    "name": "Microprocesseur",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#4cffb0",
    "rarity": 4,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Component",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Microprocessor"
  },
  "opticalGlass": {
    "name": "Verre optique",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#d8f4ff",
    "rarity": 2,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Component",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Opticalglass"
  },
  "laserLens": {
    "name": "Lentille laser",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#f0e0ff",
    "rarity": 3,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Component",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Laserlens"
  },
  "lithiumBattery": {
    "name": "Batterie lithium-ion",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#ff8fb3",
    "rarity": 3,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Component",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Lithiumbattery"
  },
  "fuelCell": {
    "name": "Cellule à combustible",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#8ee8ff",
    "rarity": 3,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Component",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Fuelcell"
  },
  "refinedFuel": {
    "name": "Carburant raffiné",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#c08442",
    "rarity": 2,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Component",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Refinedfuel"
  },
  "biofuel": {
    "name": "Biocarburant",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#78d45a",
    "rarity": 2,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Component",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Biofuel"
  },
  "propellant": {
    "name": "Propergol",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#9edfff",
    "rarity": 3,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Component",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Propellant"
  },
  "turbine": {
    "name": "Turbine",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#b7bdc8",
    "rarity": 3,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Component",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Turbine"
  },
  "industrialPump": {
    "name": "Pompe industrielle",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#9aa4af",
    "rarity": 3,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Component",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Industrialpump"
  },
  "electricMotor": {
    "name": "Moteur électrique",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#9cc0e0",
    "rarity": 3,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Component",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Electricmotor"
  },
  "servomotor": {
    "name": "Servomoteur",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#a0bad0",
    "rarity": 3,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Component",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Servomotor"
  },
  "fuelInjector": {
    "name": "Injecteur de carburant",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#d0a36c",
    "rarity": 3,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Component",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Fuelinjector"
  },
  "fuelRod": {
    "name": "Barre de combustible",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#b6ff5c",
    "rarity": 4,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Component",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Fuelrod"
  },
  "thermalCeramic": {
    "name": "Céramique thermique",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#d8cdb0",
    "rarity": 3,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Component",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Thermalceramic"
  },
  "carbonFiber": {
    "name": "Fibre de carbone",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#555a60",
    "rarity": 3,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Component",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Carbonfiber"
  },
  "compositeArmor": {
    "name": "Blindage composite",
    "cargoPerUnit": 1,
    "sellPrice": 0,
    "colorHex": "#78808a",
    "rarity": 4,
    "baseWeight": 0.0,
    "spawnTier": 0,
    "shapeClass": "Component",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "Compositearmor"
  },
  "logisticDroneBasic": {
    "name": "Drone logistique basique",
    "cargoPerUnit": 5,
    "sellPrice": 0,
    "colorHex": "#7fdcff",
    "rarity": 3,
    "baseWeight": 0,
    "spawnTier": 0,
    "shapeClass": "Component",
    "hardnessMultiplier": 1.0,
    "armorBias": 0,
    "resistBias": 0,
    "enemyCommonDrop": false,
    "id": "LogisticDroneBasic"
  },
  "ice": {
    "name": "Glace d'eau",
    "cargoPerUnit": 1,
    "sellPrice": 4,
    "colorHex": "#add8e6",
    "rarity": 1,
    "baseWeight": 1.45,
    "spawnTier": 1,
    "shapeClass": "Ice",
    "hardnessMultiplier": 0.82,
    "armorBias": -0.6,
    "resistBias": -0.06,
    "enemyCommonDrop": true,
    "id": "Ice",
    "legacy": true
  },
  "uranite": {
    "name": "Uraninite",
    "cargoPerUnit": 1,
    "sellPrice": 24,
    "colorHex": "#adff2f",
    "rarity": 4,
    "baseWeight": 0.8,
    "spawnTier": 6,
    "shapeClass": "Rock",
    "hardnessMultiplier": 1.12,
    "armorBias": 0.45,
    "resistBias": 0.04,
    "enemyCommonDrop": false,
    "id": "Uranite",
    "legacy": true
  },
  "plasmaGel": {
    "name": "Hydrogène liquide",
    "cargoPerUnit": 1,
    "sellPrice": 15,
    "colorHex": "#00bfff",
    "rarity": 3,
    "baseWeight": 0.95,
    "spawnTier": 4,
    "shapeClass": "Exotic",
    "hardnessMultiplier": 0.95,
    "armorBias": 0.0,
    "resistBias": 0.03,
    "enemyCommonDrop": true,
    "id": "PlasmaGel",
    "legacy": true
  },
  "crystal": {
    "name": "Quartz",
    "cargoPerUnit": 1,
    "sellPrice": 12,
    "colorHex": "#ee82ee",
    "rarity": 3,
    "baseWeight": 1.0,
    "spawnTier": 4,
    "shapeClass": "Crystal",
    "hardnessMultiplier": 1.16,
    "armorBias": 0.35,
    "resistBias": 0.05,
    "enemyCommonDrop": true,
    "id": "Crystal",
    "legacy": true
  },
  "bioFiber": {
    "name": "Cellulose",
    "cargoPerUnit": 1,
    "sellPrice": 20,
    "colorHex": "#90ee90",
    "rarity": 3,
    "baseWeight": 0.9,
    "spawnTier": 5,
    "shapeClass": "Biomass",
    "hardnessMultiplier": 0.94,
    "armorBias": 0.0,
    "resistBias": 0.02,
    "enemyCommonDrop": false,
    "id": "BioFiber",
    "legacy": true
  },
  "darkMatter": {
    "name": "Ilménite",
    "cargoPerUnit": 1,
    "sellPrice": 71,
    "colorHex": "#9370db",
    "rarity": 5,
    "baseWeight": 0.48,
    "spawnTier": 9,
    "shapeClass": "Exotic",
    "hardnessMultiplier": 1.18,
    "armorBias": 0.55,
    "resistBias": 0.08,
    "enemyCommonDrop": false,
    "id": "DarkMatter",
    "legacy": true
  },
  "nanoDust": {
    "name": "Silice fine",
    "cargoPerUnit": 1,
    "sellPrice": 18,
    "colorHex": "#f0e68c",
    "rarity": 2,
    "baseWeight": 1.2,
    "spawnTier": 2,
    "shapeClass": "Dust",
    "hardnessMultiplier": 0.95,
    "armorBias": -0.1,
    "resistBias": 0.0,
    "enemyCommonDrop": true,
    "id": "NanoDust",
    "legacy": true
  },
  "alloy": {
    "name": "Acier allié",
    "cargoPerUnit": 1,
    "sellPrice": 53,
    "colorHex": "#708090",
    "rarity": 4,
    "baseWeight": 0.65,
    "spawnTier": 7,
    "shapeClass": "Junk",
    "hardnessMultiplier": 1.08,
    "armorBias": 0.45,
    "resistBias": 0.04,
    "enemyCommonDrop": false,
    "id": "Alloy",
    "legacy": true
  },
  "circuit": {
    "name": "Circuit imprimé",
    "cargoPerUnit": 1,
    "sellPrice": 53,
    "colorHex": "#00ff00",
    "rarity": 4,
    "baseWeight": 0.65,
    "spawnTier": 7,
    "shapeClass": "Junk",
    "hardnessMultiplier": 1.02,
    "armorBias": 0.15,
    "resistBias": 0.04,
    "enemyCommonDrop": false,
    "id": "Circuit",
    "legacy": true
  },
  "core": {
    "name": "Barre de combustible",
    "cargoPerUnit": 1,
    "sellPrice": 88,
    "colorHex": "#ffa500",
    "rarity": 6,
    "baseWeight": 0.33,
    "spawnTier": 10,
    "shapeClass": "Exotic",
    "hardnessMultiplier": 1.25,
    "armorBias": 0.8,
    "resistBias": 0.1,
    "enemyCommonDrop": false,
    "id": "Core",
    "legacy": true
  },
  "flux": {
    "name": "Fondant boraté",
    "cargoPerUnit": 1,
    "sellPrice": 22,
    "colorHex": "#ff69b4",
    "rarity": 4,
    "baseWeight": 0.9,
    "spawnTier": 6,
    "shapeClass": "Exotic",
    "hardnessMultiplier": 1.0,
    "armorBias": 0.1,
    "resistBias": 0.05,
    "enemyCommonDrop": true,
    "id": "Flux",
    "legacy": true
  },
  "antimatter": {
    "name": "Antimatière",
    "cargoPerUnit": 1,
    "sellPrice": 88,
    "colorHex": "#f5f5f5",
    "rarity": 6,
    "baseWeight": 0.35,
    "spawnTier": 10,
    "shapeClass": "Exotic",
    "hardnessMultiplier": 1.22,
    "armorBias": 0.7,
    "resistBias": 0.1,
    "enemyCommonDrop": false,
    "id": "Antimatter",
    "legacy": true
  },
  "relic": {
    "name": "Or natif",
    "cargoPerUnit": 1,
    "sellPrice": 119,
    "colorHex": "#ffd700",
    "rarity": 7,
    "baseWeight": 0.08,
    "spawnTier": 15,
    "shapeClass": "Exotic",
    "hardnessMultiplier": 1.5,
    "armorBias": 1.2,
    "resistBias": 0.15,
    "enemyCommonDrop": false,
    "id": "Relic",
    "legacy": true
  },
  "ironVein": {
    "name": "Hématite",
    "cargoPerUnit": 1,
    "sellPrice": 11,
    "colorHex": "#a9a9a9",
    "rarity": 1,
    "baseWeight": 1.2,
    "spawnTier": 1,
    "shapeClass": "Rock",
    "hardnessMultiplier": 0.96,
    "armorBias": 0.2,
    "resistBias": 0.0,
    "enemyCommonDrop": true,
    "id": "IronVein",
    "legacy": true
  },
  "nickelShard": {
    "name": "Minerai de nickel",
    "cargoPerUnit": 1,
    "sellPrice": 20,
    "colorHex": "#dcdcdc",
    "rarity": 2,
    "baseWeight": 1.05,
    "spawnTier": 2,
    "shapeClass": "Rock",
    "hardnessMultiplier": 1.02,
    "armorBias": 0.2,
    "resistBias": 0.01,
    "enemyCommonDrop": true,
    "id": "NickelShard",
    "legacy": true
  },
  "vanadiumGlass": {
    "name": "Vanadinite",
    "cargoPerUnit": 1,
    "sellPrice": 37,
    "colorHex": "#008080",
    "rarity": 3,
    "baseWeight": 0.85,
    "spawnTier": 5,
    "shapeClass": "Crystal",
    "hardnessMultiplier": 1.14,
    "armorBias": 0.4,
    "resistBias": 0.05,
    "enemyCommonDrop": false,
    "id": "VanadiumGlass",
    "legacy": true
  },
  "heliumIce": {
    "name": "Glace d'hélium-3",
    "cargoPerUnit": 1,
    "sellPrice": 23,
    "colorHex": "#f0f8ff",
    "rarity": 2,
    "baseWeight": 1.0,
    "spawnTier": 3,
    "shapeClass": "Ice",
    "hardnessMultiplier": 0.83,
    "armorBias": -0.55,
    "resistBias": -0.06,
    "enemyCommonDrop": false,
    "id": "HeliumIce",
    "legacy": true
  },
  "sulfurStone": {
    "name": "Soufre natif",
    "cargoPerUnit": 1,
    "sellPrice": 11,
    "colorHex": "#ffff00",
    "rarity": 1,
    "baseWeight": 1.15,
    "spawnTier": 1,
    "shapeClass": "Rock",
    "hardnessMultiplier": 0.9,
    "armorBias": 0.0,
    "resistBias": -0.01,
    "enemyCommonDrop": true,
    "id": "SulfurStone",
    "legacy": true
  },
  "carbonMesh": {
    "name": "Fibre de carbone",
    "cargoPerUnit": 1,
    "sellPrice": 34,
    "colorHex": "#696969",
    "rarity": 3,
    "baseWeight": 0.95,
    "spawnTier": 4,
    "shapeClass": "Junk",
    "hardnessMultiplier": 1.03,
    "armorBias": 0.2,
    "resistBias": 0.02,
    "enemyCommonDrop": true,
    "id": "CarbonMesh",
    "legacy": true
  },
  "quartzBloom": {
    "name": "Quartz rose",
    "cargoPerUnit": 1,
    "sellPrice": 23,
    "colorHex": "#dda0dd",
    "rarity": 2,
    "baseWeight": 0.95,
    "spawnTier": 3,
    "shapeClass": "Crystal",
    "hardnessMultiplier": 1.08,
    "armorBias": 0.3,
    "resistBias": 0.04,
    "enemyCommonDrop": false,
    "id": "QuartzBloom",
    "legacy": true
  },
  "lithiumSalt": {
    "name": "Carbonate de lithium",
    "cargoPerUnit": 1,
    "sellPrice": 23,
    "colorHex": "#ffb6c1",
    "rarity": 2,
    "baseWeight": 1.0,
    "spawnTier": 3,
    "shapeClass": "Dust",
    "hardnessMultiplier": 0.92,
    "armorBias": 0.0,
    "resistBias": 0.01,
    "enemyCommonDrop": true,
    "id": "LithiumSalt",
    "legacy": true
  },
  "palladiumDust": {
    "name": "Palladium",
    "cargoPerUnit": 1,
    "sellPrice": 50,
    "colorHex": "#eee8aa",
    "rarity": 4,
    "baseWeight": 0.8,
    "spawnTier": 6,
    "shapeClass": "Dust",
    "hardnessMultiplier": 1.05,
    "armorBias": 0.25,
    "resistBias": 0.03,
    "enemyCommonDrop": false,
    "id": "PalladiumDust",
    "legacy": true
  },
  "neodymCluster": {
    "name": "Bastnäsite",
    "cargoPerUnit": 1,
    "sellPrice": 50,
    "colorHex": "#48d1cc",
    "rarity": 4,
    "baseWeight": 0.75,
    "spawnTier": 6,
    "shapeClass": "Crystal",
    "hardnessMultiplier": 1.08,
    "armorBias": 0.25,
    "resistBias": 0.04,
    "enemyCommonDrop": false,
    "id": "NeodymCluster",
    "legacy": true
  },
  "osmiumSpine": {
    "name": "Osmium",
    "cargoPerUnit": 1,
    "sellPrice": 53,
    "colorHex": "#6a5acd",
    "rarity": 4,
    "baseWeight": 0.65,
    "spawnTier": 7,
    "shapeClass": "Rock",
    "hardnessMultiplier": 1.2,
    "armorBias": 0.9,
    "resistBias": 0.05,
    "enemyCommonDrop": false,
    "id": "OsmiumSpine",
    "legacy": true
  },
  "iridiumPearl": {
    "name": "Iridium",
    "cargoPerUnit": 1,
    "sellPrice": 68,
    "colorHex": "#e6e6fa",
    "rarity": 5,
    "baseWeight": 0.5,
    "spawnTier": 8,
    "shapeClass": "Crystal",
    "hardnessMultiplier": 1.24,
    "armorBias": 0.95,
    "resistBias": 0.06,
    "enemyCommonDrop": false,
    "id": "IridiumPearl",
    "legacy": true
  },
  "xenonPearl": {
    "name": "Xénon solide",
    "cargoPerUnit": 1,
    "sellPrice": 53,
    "colorHex": "#e0ffff",
    "rarity": 4,
    "baseWeight": 0.65,
    "spawnTier": 7,
    "shapeClass": "Crystal",
    "hardnessMultiplier": 1.06,
    "armorBias": 0.3,
    "resistBias": 0.05,
    "enemyCommonDrop": false,
    "id": "XenonPearl",
    "legacy": true
  },
  "voidAmber": {
    "name": "Ambre",
    "cargoPerUnit": 1,
    "sellPrice": 68,
    "colorHex": "#ff8c00",
    "rarity": 5,
    "baseWeight": 0.58,
    "spawnTier": 8,
    "shapeClass": "Exotic",
    "hardnessMultiplier": 1.14,
    "armorBias": 0.45,
    "resistBias": 0.07,
    "enemyCommonDrop": false,
    "id": "VoidAmber",
    "legacy": true
  },
  "phaseQuartz": {
    "name": "Améthyste",
    "cargoPerUnit": 1,
    "sellPrice": 68,
    "colorHex": "#ba55d3",
    "rarity": 5,
    "baseWeight": 0.58,
    "spawnTier": 8,
    "shapeClass": "Crystal",
    "hardnessMultiplier": 1.2,
    "armorBias": 0.45,
    "resistBias": 0.08,
    "enemyCommonDrop": false,
    "id": "PhaseQuartz",
    "legacy": true
  },
  "echoResin": {
    "name": "Résine",
    "cargoPerUnit": 1,
    "sellPrice": 34,
    "colorHex": "#2e8b57",
    "rarity": 3,
    "baseWeight": 0.9,
    "spawnTier": 4,
    "shapeClass": "Biomass",
    "hardnessMultiplier": 0.95,
    "armorBias": 0.0,
    "resistBias": 0.03,
    "enemyCommonDrop": false,
    "id": "EchoResin",
    "legacy": true
  },
  "stellarAsh": {
    "name": "Cendre volcanique",
    "cargoPerUnit": 1,
    "sellPrice": 34,
    "colorHex": "#778899",
    "rarity": 3,
    "baseWeight": 0.95,
    "spawnTier": 4,
    "shapeClass": "Dust",
    "hardnessMultiplier": 0.9,
    "armorBias": -0.2,
    "resistBias": -0.02,
    "enemyCommonDrop": false,
    "id": "StellarAsh",
    "legacy": true
  },
  "gravitonFilament": {
    "name": "Tungstène filé",
    "cargoPerUnit": 1,
    "sellPrice": 88,
    "colorHex": "#87cefa",
    "rarity": 6,
    "baseWeight": 0.32,
    "spawnTier": 10,
    "shapeClass": "Exotic",
    "hardnessMultiplier": 1.23,
    "armorBias": 0.75,
    "resistBias": 0.1,
    "enemyCommonDrop": false,
    "id": "GravitonFilament",
    "legacy": true
  },
  "chronoShard": {
    "name": "Zircone",
    "cargoPerUnit": 1,
    "sellPrice": 88,
    "colorHex": "#ffe4b5",
    "rarity": 6,
    "baseWeight": 0.31,
    "spawnTier": 10,
    "shapeClass": "Crystal",
    "hardnessMultiplier": 1.24,
    "armorBias": 0.8,
    "resistBias": 0.1,
    "enemyCommonDrop": false,
    "id": "ChronoShard",
    "legacy": true
  },
  "prismTear": {
    "name": "Fluorite",
    "cargoPerUnit": 1,
    "sellPrice": 91,
    "colorHex": "#ff00ff",
    "rarity": 6,
    "baseWeight": 0.27,
    "spawnTier": 11,
    "shapeClass": "Crystal",
    "hardnessMultiplier": 1.28,
    "armorBias": 0.85,
    "resistBias": 0.11,
    "enemyCommonDrop": false,
    "id": "PrismTear",
    "legacy": true
  },
  "singularitySeed": {
    "name": "Silicium monocristallin",
    "cargoPerUnit": 1,
    "sellPrice": 116,
    "colorHex": "#000000",
    "rarity": 7,
    "baseWeight": 0.12,
    "spawnTier": 14,
    "shapeClass": "Exotic",
    "hardnessMultiplier": 1.45,
    "armorBias": 1.25,
    "resistBias": 0.16,
    "enemyCommonDrop": false,
    "id": "SingularitySeed",
    "legacy": true
  },
  "aetherFoam": {
    "name": "Aérogel de silice",
    "cargoPerUnit": 1,
    "sellPrice": 91,
    "colorHex": "#f0ffff",
    "rarity": 6,
    "baseWeight": 0.27,
    "spawnTier": 11,
    "shapeClass": "Exotic",
    "hardnessMultiplier": 1.18,
    "armorBias": 0.45,
    "resistBias": 0.11,
    "enemyCommonDrop": false,
    "id": "AetherFoam",
    "legacy": true
  },
  "nullGlass": {
    "name": "Obsidienne",
    "cargoPerUnit": 1,
    "sellPrice": 71,
    "colorHex": "#9400d3",
    "rarity": 5,
    "baseWeight": 0.45,
    "spawnTier": 9,
    "shapeClass": "Crystal",
    "hardnessMultiplier": 1.3,
    "armorBias": 1.1,
    "resistBias": 0.1,
    "enemyCommonDrop": false,
    "id": "NullGlass",
    "legacy": true
  },
  "basaltChunk": {
    "name": "Basalte",
    "cargoPerUnit": 1,
    "sellPrice": 40,
    "colorHex": "#5c5c60",
    "rarity": 1,
    "baseWeight": 1.1,
    "spawnTier": 1,
    "shapeClass": "Rock",
    "hardnessMultiplier": 1.02,
    "armorBias": 0.3,
    "resistBias": 0.01,
    "enemyCommonDrop": true,
    "id": "BasaltChunk",
    "legacy": true
  },
  "manganeseNodule": {
    "name": "Concrétion manganésifère",
    "cargoPerUnit": 1,
    "sellPrice": 40,
    "colorHex": "#866a5d",
    "rarity": 2,
    "baseWeight": 1.0,
    "spawnTier": 2,
    "shapeClass": "Rock",
    "hardnessMultiplier": 1.05,
    "armorBias": 0.25,
    "resistBias": 0.01,
    "enemyCommonDrop": true,
    "id": "ManganeseNodule",
    "legacy": true
  },
  "boronFlake": {
    "name": "Borax",
    "cargoPerUnit": 1,
    "sellPrice": 40,
    "colorHex": "#ffd68c",
    "rarity": 2,
    "baseWeight": 0.9,
    "spawnTier": 3,
    "shapeClass": "Crystal",
    "hardnessMultiplier": 1.02,
    "armorBias": 0.1,
    "resistBias": 0.02,
    "enemyCommonDrop": false,
    "id": "BoronFlake",
    "legacy": true
  },
  "phosphorite": {
    "name": "Phosphorite",
    "cargoPerUnit": 1,
    "sellPrice": 40,
    "colorHex": "#d7d49c",
    "rarity": 2,
    "baseWeight": 0.95,
    "spawnTier": 2,
    "shapeClass": "Rock",
    "hardnessMultiplier": 0.95,
    "armorBias": 0.0,
    "resistBias": 0.0,
    "enemyCommonDrop": false,
    "id": "Phosphorite",
    "legacy": true
  },
  "sodiumClathrate": {
    "name": "Natron",
    "cargoPerUnit": 1,
    "sellPrice": 40,
    "colorHex": "#d2e9ff",
    "rarity": 2,
    "baseWeight": 0.95,
    "spawnTier": 3,
    "shapeClass": "Ice",
    "hardnessMultiplier": 0.86,
    "armorBias": -0.35,
    "resistBias": -0.03,
    "enemyCommonDrop": false,
    "id": "SodiumClathrate",
    "legacy": true
  },
  "argonIce": {
    "name": "Argon solide",
    "cargoPerUnit": 1,
    "sellPrice": 40,
    "colorHex": "#c6f0ff",
    "rarity": 2,
    "baseWeight": 0.85,
    "spawnTier": 3,
    "shapeClass": "Ice",
    "hardnessMultiplier": 0.84,
    "armorBias": -0.45,
    "resistBias": -0.04,
    "enemyCommonDrop": false,
    "id": "ArgonIce",
    "legacy": true
  },
  "ceresClay": {
    "name": "Argile",
    "cargoPerUnit": 1,
    "sellPrice": 40,
    "colorHex": "#aa876c",
    "rarity": 1,
    "baseWeight": 1.05,
    "spawnTier": 1,
    "shapeClass": "Dust",
    "hardnessMultiplier": 0.88,
    "armorBias": -0.2,
    "resistBias": -0.01,
    "enemyCommonDrop": true,
    "id": "CeresClay",
    "legacy": true
  },
  "grapheneVeil": {
    "name": "Graphène",
    "cargoPerUnit": 1,
    "sellPrice": 40,
    "colorHex": "#464655",
    "rarity": 3,
    "baseWeight": 0.85,
    "spawnTier": 5,
    "shapeClass": "Junk",
    "hardnessMultiplier": 1.05,
    "armorBias": 0.25,
    "resistBias": 0.03,
    "enemyCommonDrop": true,
    "id": "GrapheneVeil",
    "legacy": true
  },
  "tungstenOre": {
    "name": "Minerai de tungstène",
    "cargoPerUnit": 1,
    "sellPrice": 40,
    "colorHex": "#82919b",
    "rarity": 3,
    "baseWeight": 0.75,
    "spawnTier": 5,
    "shapeClass": "Rock",
    "hardnessMultiplier": 1.18,
    "armorBias": 0.65,
    "resistBias": 0.04,
    "enemyCommonDrop": false,
    "id": "TungstenOre",
    "legacy": true
  },
  "rutileShard": {
    "name": "Rutile",
    "cargoPerUnit": 1,
    "sellPrice": 40,
    "colorHex": "#cdaa78",
    "rarity": 3,
    "baseWeight": 0.8,
    "spawnTier": 5,
    "shapeClass": "Crystal",
    "hardnessMultiplier": 1.08,
    "armorBias": 0.25,
    "resistBias": 0.04,
    "enemyCommonDrop": false,
    "id": "RutileShard",
    "legacy": true
  },
  "galliumBloom": {
    "name": "Gallium",
    "cargoPerUnit": 1,
    "sellPrice": 40,
    "colorHex": "#aebfff",
    "rarity": 4,
    "baseWeight": 0.78,
    "spawnTier": 6,
    "shapeClass": "Crystal",
    "hardnessMultiplier": 1.03,
    "armorBias": 0.2,
    "resistBias": 0.04,
    "enemyCommonDrop": false,
    "id": "GalliumBloom",
    "legacy": true
  },
  "seleniumThread": {
    "name": "Sélénium",
    "cargoPerUnit": 1,
    "sellPrice": 40,
    "colorHex": "#ffbc78",
    "rarity": 4,
    "baseWeight": 0.78,
    "spawnTier": 6,
    "shapeClass": "Junk",
    "hardnessMultiplier": 1.04,
    "armorBias": 0.2,
    "resistBias": 0.04,
    "enemyCommonDrop": false,
    "id": "SeleniumThread",
    "legacy": true
  },
  "hafniumPlate": {
    "name": "Plaque d'hafnium",
    "cargoPerUnit": 1,
    "sellPrice": 40,
    "colorHex": "#97a6b4",
    "rarity": 4,
    "baseWeight": 0.6,
    "spawnTier": 7,
    "shapeClass": "Junk",
    "hardnessMultiplier": 1.16,
    "armorBias": 0.75,
    "resistBias": 0.04,
    "enemyCommonDrop": false,
    "id": "HafniumPlate",
    "legacy": true
  },
  "rutheniumDust": {
    "name": "Ruthénium",
    "cargoPerUnit": 1,
    "sellPrice": 40,
    "colorHex": "#b4bcc0",
    "rarity": 4,
    "baseWeight": 0.62,
    "spawnTier": 7,
    "shapeClass": "Dust",
    "hardnessMultiplier": 1.08,
    "armorBias": 0.45,
    "resistBias": 0.04,
    "enemyCommonDrop": false,
    "id": "RutheniumDust",
    "legacy": true
  },
  "telluricGlass": {
    "name": "Tellure",
    "cargoPerUnit": 1,
    "sellPrice": 40,
    "colorHex": "#76e1cd",
    "rarity": 5,
    "baseWeight": 0.55,
    "spawnTier": 8,
    "shapeClass": "Crystal",
    "hardnessMultiplier": 1.16,
    "armorBias": 0.55,
    "resistBias": 0.07,
    "enemyCommonDrop": false,
    "id": "TelluricGlass",
    "legacy": true
  },
  "mercuryIce": {
    "name": "Mercure",
    "cargoPerUnit": 1,
    "sellPrice": 40,
    "colorHex": "#d6e0ea",
    "rarity": 5,
    "baseWeight": 0.52,
    "spawnTier": 8,
    "shapeClass": "Ice",
    "hardnessMultiplier": 1.03,
    "armorBias": 0.1,
    "resistBias": 0.05,
    "enemyCommonDrop": false,
    "id": "MercuryIce",
    "legacy": true
  },
  "cesiumSalt": {
    "name": "Formiate de césium",
    "cargoPerUnit": 1,
    "sellPrice": 40,
    "colorHex": "#ece1ff",
    "rarity": 4,
    "baseWeight": 0.62,
    "spawnTier": 7,
    "shapeClass": "Dust",
    "hardnessMultiplier": 0.95,
    "armorBias": 0.1,
    "resistBias": 0.04,
    "enemyCommonDrop": false,
    "id": "CesiumSalt",
    "legacy": true
  },
  "lanthanumKnot": {
    "name": "Monazite",
    "cargoPerUnit": 1,
    "sellPrice": 40,
    "colorHex": "#ace8d6",
    "rarity": 5,
    "baseWeight": 0.5,
    "spawnTier": 8,
    "shapeClass": "Exotic",
    "hardnessMultiplier": 1.08,
    "armorBias": 0.3,
    "resistBias": 0.07,
    "enemyCommonDrop": false,
    "id": "LanthanumKnot",
    "legacy": true
  },
  "yttriumPrism": {
    "name": "Xénotime",
    "cargoPerUnit": 1,
    "sellPrice": 40,
    "colorHex": "#c4faff",
    "rarity": 5,
    "baseWeight": 0.44,
    "spawnTier": 9,
    "shapeClass": "Crystal",
    "hardnessMultiplier": 1.18,
    "armorBias": 0.45,
    "resistBias": 0.08,
    "enemyCommonDrop": false,
    "id": "YttriumPrism",
    "legacy": true
  },
  "zirconCore": {
    "name": "Zircon",
    "cargoPerUnit": 1,
    "sellPrice": 40,
    "colorHex": "#ebf2ff",
    "rarity": 5,
    "baseWeight": 0.42,
    "spawnTier": 9,
    "shapeClass": "Crystal",
    "hardnessMultiplier": 1.18,
    "armorBias": 0.55,
    "resistBias": 0.08,
    "enemyCommonDrop": false,
    "id": "ZirconCore",
    "legacy": true
  },
  "quasarPollen": {
    "name": "Soufre sublimé",
    "cargoPerUnit": 1,
    "sellPrice": 40,
    "colorHex": "#fff596",
    "rarity": 6,
    "baseWeight": 0.25,
    "spawnTier": 11,
    "shapeClass": "Dust",
    "hardnessMultiplier": 1.15,
    "armorBias": 0.6,
    "resistBias": 0.11,
    "enemyCommonDrop": false,
    "id": "QuasarPollen",
    "legacy": true
  },
  "eventidePearl": {
    "name": "Opale noire",
    "cargoPerUnit": 1,
    "sellPrice": 40,
    "colorHex": "#d2b4ff",
    "rarity": 6,
    "baseWeight": 0.22,
    "spawnTier": 12,
    "shapeClass": "Crystal",
    "hardnessMultiplier": 1.25,
    "armorBias": 0.9,
    "resistBias": 0.12,
    "enemyCommonDrop": false,
    "id": "EventidePearl",
    "legacy": true
  },
  "vacuumLotus": {
    "name": "Kelp séché",
    "cargoPerUnit": 1,
    "sellPrice": 40,
    "colorHex": "#affff0",
    "rarity": 6,
    "baseWeight": 0.2,
    "spawnTier": 12,
    "shapeClass": "Biomass",
    "hardnessMultiplier": 1.12,
    "armorBias": 0.45,
    "resistBias": 0.12,
    "enemyCommonDrop": false,
    "id": "VacuumLotus",
    "legacy": true
  },
  "entropySpore": {
    "name": "Spores fongiques",
    "cargoPerUnit": 1,
    "sellPrice": 40,
    "colorHex": "#82ffa0",
    "rarity": 7,
    "baseWeight": 0.16,
    "spawnTier": 13,
    "shapeClass": "Biomass",
    "hardnessMultiplier": 1.28,
    "armorBias": 0.95,
    "resistBias": 0.14,
    "enemyCommonDrop": false,
    "id": "EntropySpore",
    "legacy": true
  },
  "lumenMoss": {
    "name": "Lichen",
    "cargoPerUnit": 1,
    "sellPrice": 40,
    "colorHex": "#98ff7c",
    "rarity": 3,
    "baseWeight": 0.78,
    "spawnTier": 5,
    "shapeClass": "Biomass",
    "hardnessMultiplier": 0.9,
    "armorBias": -0.1,
    "resistBias": 0.03,
    "enemyCommonDrop": false,
    "id": "LumenMoss",
    "legacy": true
  },
  "magnetarSkin": {
    "name": "Magnétite",
    "cargoPerUnit": 1,
    "sellPrice": 40,
    "colorHex": "#6eaaff",
    "rarity": 7,
    "baseWeight": 0.06,
    "spawnTier": 16,
    "shapeClass": "Exotic",
    "hardnessMultiplier": 1.55,
    "armorBias": 1.35,
    "resistBias": 0.17,
    "enemyCommonDrop": false,
    "id": "MagnetarSkin",
    "legacy": true
  }
};
export function getResourceRarityScore(key){ return RESOURCE_DEFS[key]?.rarity ?? 1; }
export function getResourceDef(key){ return RESOURCE_DEFS[key] || null; }
export function isKnownResource(key){ return !!RESOURCE_DEFS[key]; }
