export const RESOURCE_KEYS_ORDER = [
  "scrap",
  "ice",
  "copper",
  "silicon",
  "uranite",
  "plasmaGel",
  "crystal",
  "bioFiber",
  "darkMatter",
  "nanoDust",
  "alloy",
  "circuit",
  "core",
  "flux",
  "antimatter",
  "relic",
  "ironVein",
  "cobaltOre",
  "nickelShard",
  "titaniumOre",
  "vanadiumGlass",
  "heliumIce",
  "sulfurStone",
  "carbonMesh",
  "quartzBloom",
  "lithiumSalt",
  "palladiumDust",
  "neodymCluster",
  "osmiumSpine",
  "iridiumPearl",
  "xenonPearl",
  "voidAmber",
  "phaseQuartz",
  "echoResin",
  "stellarAsh",
  "gravitonFilament",
  "chronoShard",
  "prismTear",
  "singularitySeed",
  "aetherFoam",
  "nullGlass",
  "basaltChunk",
  "manganeseNodule",
  "boronFlake",
  "phosphorite",
  "sodiumClathrate",
  "argonIce",
  "ceresClay",
  "grapheneVeil",
  "tungstenOre",
  "rutileShard",
  "galliumBloom",
  "seleniumThread",
  "hafniumPlate",
  "rutheniumDust",
  "telluricGlass",
  "mercuryIce",
  "cesiumSalt",
  "lanthanumKnot",
  "yttriumPrism",
  "zirconCore",
  "quasarPollen",
  "eventidePearl",
  "vacuumLotus",
  "entropySpore",
  "lumenMoss",
  "magnetarSkin"
];
export const RESOURCE_DEFS = {
  scrap: {"name": "Ferraille", "cargoPerUnit": 1, "sellPrice": 3, "colorHex": "#c0c0c0", "rarity": 1, "baseWeight": 1.6, "spawnTier": 1, "shapeClass": "Junk", "hardnessMultiplier": 0.85, "armorBias": -0.4, "resistBias": -0.03, "enemyCommonDrop": true, "id": "Scrap"},
  ice: {"name": "Glace d'eau", "cargoPerUnit": 1, "sellPrice": 4, "colorHex": "#add8e6", "rarity": 1, "baseWeight": 1.45, "spawnTier": 1, "shapeClass": "Ice", "hardnessMultiplier": 0.82, "armorBias": -0.6, "resistBias": -0.06, "enemyCommonDrop": true, "id": "Ice"},
  copper: {"name": "Cuivre", "cargoPerUnit": 1, "sellPrice": 5, "colorHex": "#cd853f", "rarity": 1, "baseWeight": 1.35, "spawnTier": 1, "shapeClass": "Rock", "hardnessMultiplier": 0.92, "armorBias": -0.2, "resistBias": 0.0, "enemyCommonDrop": true, "id": "Copper"},
  silicon: {"name": "Silicium", "cargoPerUnit": 1, "sellPrice": 6, "colorHex": "#d3d3d3", "rarity": 2, "baseWeight": 1.25, "spawnTier": 2, "shapeClass": "Rock", "hardnessMultiplier": 1.0, "armorBias": 0.15, "resistBias": 0.01, "enemyCommonDrop": true, "id": "Silicon"},
  uranite: {"name": "Uraninite", "cargoPerUnit": 1, "sellPrice": 24, "colorHex": "#adff2f", "rarity": 4, "baseWeight": 0.8, "spawnTier": 6, "shapeClass": "Rock", "hardnessMultiplier": 1.12, "armorBias": 0.45, "resistBias": 0.04, "enemyCommonDrop": false, "id": "Uranite"},
  plasmaGel: {"name": "Hydrogène liquide", "cargoPerUnit": 1, "sellPrice": 15, "colorHex": "#00bfff", "rarity": 3, "baseWeight": 0.95, "spawnTier": 4, "shapeClass": "Exotic", "hardnessMultiplier": 0.95, "armorBias": 0.0, "resistBias": 0.03, "enemyCommonDrop": true, "id": "PlasmaGel"},
  crystal: {"name": "Quartz", "cargoPerUnit": 1, "sellPrice": 12, "colorHex": "#ee82ee", "rarity": 3, "baseWeight": 1.0, "spawnTier": 4, "shapeClass": "Crystal", "hardnessMultiplier": 1.16, "armorBias": 0.35, "resistBias": 0.05, "enemyCommonDrop": true, "id": "Crystal"},
  bioFiber: {"name": "Cellulose", "cargoPerUnit": 1, "sellPrice": 20, "colorHex": "#90ee90", "rarity": 3, "baseWeight": 0.9, "spawnTier": 5, "shapeClass": "Biomass", "hardnessMultiplier": 0.94, "armorBias": 0.0, "resistBias": 0.02, "enemyCommonDrop": false, "id": "BioFiber"},
  darkMatter: {"name": "Ilménite", "cargoPerUnit": 1, "sellPrice": 71, "colorHex": "#9370db", "rarity": 5, "baseWeight": 0.48, "spawnTier": 9, "shapeClass": "Exotic", "hardnessMultiplier": 1.18, "armorBias": 0.55, "resistBias": 0.08, "enemyCommonDrop": false, "id": "DarkMatter"},
  nanoDust: {"name": "Silice fine", "cargoPerUnit": 1, "sellPrice": 18, "colorHex": "#f0e68c", "rarity": 2, "baseWeight": 1.2, "spawnTier": 2, "shapeClass": "Dust", "hardnessMultiplier": 0.95, "armorBias": -0.1, "resistBias": 0.0, "enemyCommonDrop": true, "id": "NanoDust"},
  alloy: {"name": "Acier allié", "cargoPerUnit": 1, "sellPrice": 53, "colorHex": "#708090", "rarity": 4, "baseWeight": 0.65, "spawnTier": 7, "shapeClass": "Junk", "hardnessMultiplier": 1.08, "armorBias": 0.45, "resistBias": 0.04, "enemyCommonDrop": false, "id": "Alloy"},
  circuit: {"name": "Circuit imprimé", "cargoPerUnit": 1, "sellPrice": 53, "colorHex": "#00ff00", "rarity": 4, "baseWeight": 0.65, "spawnTier": 7, "shapeClass": "Junk", "hardnessMultiplier": 1.02, "armorBias": 0.15, "resistBias": 0.04, "enemyCommonDrop": false, "id": "Circuit"},
  core: {"name": "Barre de combustible", "cargoPerUnit": 1, "sellPrice": 88, "colorHex": "#ffa500", "rarity": 6, "baseWeight": 0.33, "spawnTier": 10, "shapeClass": "Exotic", "hardnessMultiplier": 1.25, "armorBias": 0.8, "resistBias": 0.1, "enemyCommonDrop": false, "id": "Core"},
  flux: {"name": "Fondant boraté", "cargoPerUnit": 1, "sellPrice": 22, "colorHex": "#ff69b4", "rarity": 4, "baseWeight": 0.9, "spawnTier": 6, "shapeClass": "Exotic", "hardnessMultiplier": 1.0, "armorBias": 0.1, "resistBias": 0.05, "enemyCommonDrop": true, "id": "Flux"},
  antimatter: {"name": "Antimatière", "cargoPerUnit": 1, "sellPrice": 88, "colorHex": "#f5f5f5", "rarity": 6, "baseWeight": 0.35, "spawnTier": 10, "shapeClass": "Exotic", "hardnessMultiplier": 1.22, "armorBias": 0.7, "resistBias": 0.1, "enemyCommonDrop": false, "id": "Antimatter"},
  relic: {"name": "Or natif", "cargoPerUnit": 1, "sellPrice": 119, "colorHex": "#ffd700", "rarity": 7, "baseWeight": 0.08, "spawnTier": 15, "shapeClass": "Exotic", "hardnessMultiplier": 1.5, "armorBias": 1.2, "resistBias": 0.15, "enemyCommonDrop": false, "id": "Relic"},
  ironVein: {"name": "Hématite", "cargoPerUnit": 1, "sellPrice": 11, "colorHex": "#a9a9a9", "rarity": 1, "baseWeight": 1.2, "spawnTier": 1, "shapeClass": "Rock", "hardnessMultiplier": 0.96, "armorBias": 0.2, "resistBias": 0.0, "enemyCommonDrop": true, "id": "IronVein"},
  cobaltOre: {"name": "Minerai de cobalt", "cargoPerUnit": 1, "sellPrice": 20, "colorHex": "#4169e1", "rarity": 2, "baseWeight": 1.1, "spawnTier": 2, "shapeClass": "Rock", "hardnessMultiplier": 1.05, "armorBias": 0.2, "resistBias": 0.01, "enemyCommonDrop": true, "id": "CobaltOre"},
  nickelShard: {"name": "Minerai de nickel", "cargoPerUnit": 1, "sellPrice": 20, "colorHex": "#dcdcdc", "rarity": 2, "baseWeight": 1.05, "spawnTier": 2, "shapeClass": "Rock", "hardnessMultiplier": 1.02, "armorBias": 0.2, "resistBias": 0.01, "enemyCommonDrop": true, "id": "NickelShard"},
  titaniumOre: {"name": "Minerai de titane", "cargoPerUnit": 1, "sellPrice": 34, "colorHex": "#b0c4de", "rarity": 3, "baseWeight": 0.9, "spawnTier": 4, "shapeClass": "Rock", "hardnessMultiplier": 1.12, "armorBias": 0.55, "resistBias": 0.03, "enemyCommonDrop": false, "id": "TitaniumOre"},
  vanadiumGlass: {"name": "Vanadinite", "cargoPerUnit": 1, "sellPrice": 37, "colorHex": "#008080", "rarity": 3, "baseWeight": 0.85, "spawnTier": 5, "shapeClass": "Crystal", "hardnessMultiplier": 1.14, "armorBias": 0.4, "resistBias": 0.05, "enemyCommonDrop": false, "id": "VanadiumGlass"},
  heliumIce: {"name": "Glace d'hélium-3", "cargoPerUnit": 1, "sellPrice": 23, "colorHex": "#f0f8ff", "rarity": 2, "baseWeight": 1.0, "spawnTier": 3, "shapeClass": "Ice", "hardnessMultiplier": 0.83, "armorBias": -0.55, "resistBias": -0.06, "enemyCommonDrop": false, "id": "HeliumIce"},
  sulfurStone: {"name": "Soufre natif", "cargoPerUnit": 1, "sellPrice": 11, "colorHex": "#ffff00", "rarity": 1, "baseWeight": 1.15, "spawnTier": 1, "shapeClass": "Rock", "hardnessMultiplier": 0.9, "armorBias": 0.0, "resistBias": -0.01, "enemyCommonDrop": true, "id": "SulfurStone"},
  carbonMesh: {"name": "Fibre de carbone", "cargoPerUnit": 1, "sellPrice": 34, "colorHex": "#696969", "rarity": 3, "baseWeight": 0.95, "spawnTier": 4, "shapeClass": "Junk", "hardnessMultiplier": 1.03, "armorBias": 0.2, "resistBias": 0.02, "enemyCommonDrop": true, "id": "CarbonMesh"},
  quartzBloom: {"name": "Quartz rose", "cargoPerUnit": 1, "sellPrice": 23, "colorHex": "#dda0dd", "rarity": 2, "baseWeight": 0.95, "spawnTier": 3, "shapeClass": "Crystal", "hardnessMultiplier": 1.08, "armorBias": 0.3, "resistBias": 0.04, "enemyCommonDrop": false, "id": "QuartzBloom"},
  lithiumSalt: {"name": "Carbonate de lithium", "cargoPerUnit": 1, "sellPrice": 23, "colorHex": "#ffb6c1", "rarity": 2, "baseWeight": 1.0, "spawnTier": 3, "shapeClass": "Dust", "hardnessMultiplier": 0.92, "armorBias": 0.0, "resistBias": 0.01, "enemyCommonDrop": true, "id": "LithiumSalt"},
  palladiumDust: {"name": "Palladium", "cargoPerUnit": 1, "sellPrice": 50, "colorHex": "#eee8aa", "rarity": 4, "baseWeight": 0.8, "spawnTier": 6, "shapeClass": "Dust", "hardnessMultiplier": 1.05, "armorBias": 0.25, "resistBias": 0.03, "enemyCommonDrop": false, "id": "PalladiumDust"},
  neodymCluster: {"name": "Bastnäsite", "cargoPerUnit": 1, "sellPrice": 50, "colorHex": "#48d1cc", "rarity": 4, "baseWeight": 0.75, "spawnTier": 6, "shapeClass": "Crystal", "hardnessMultiplier": 1.08, "armorBias": 0.25, "resistBias": 0.04, "enemyCommonDrop": false, "id": "NeodymCluster"},
  osmiumSpine: {"name": "Osmium", "cargoPerUnit": 1, "sellPrice": 53, "colorHex": "#6a5acd", "rarity": 4, "baseWeight": 0.65, "spawnTier": 7, "shapeClass": "Rock", "hardnessMultiplier": 1.2, "armorBias": 0.9, "resistBias": 0.05, "enemyCommonDrop": false, "id": "OsmiumSpine"},
  iridiumPearl: {"name": "Iridium", "cargoPerUnit": 1, "sellPrice": 68, "colorHex": "#e6e6fa", "rarity": 5, "baseWeight": 0.5, "spawnTier": 8, "shapeClass": "Crystal", "hardnessMultiplier": 1.24, "armorBias": 0.95, "resistBias": 0.06, "enemyCommonDrop": false, "id": "IridiumPearl"},
  xenonPearl: {"name": "Xénon solide", "cargoPerUnit": 1, "sellPrice": 53, "colorHex": "#e0ffff", "rarity": 4, "baseWeight": 0.65, "spawnTier": 7, "shapeClass": "Crystal", "hardnessMultiplier": 1.06, "armorBias": 0.3, "resistBias": 0.05, "enemyCommonDrop": false, "id": "XenonPearl"},
  voidAmber: {"name": "Ambre", "cargoPerUnit": 1, "sellPrice": 68, "colorHex": "#ff8c00", "rarity": 5, "baseWeight": 0.58, "spawnTier": 8, "shapeClass": "Exotic", "hardnessMultiplier": 1.14, "armorBias": 0.45, "resistBias": 0.07, "enemyCommonDrop": false, "id": "VoidAmber"},
  phaseQuartz: {"name": "Améthyste", "cargoPerUnit": 1, "sellPrice": 68, "colorHex": "#ba55d3", "rarity": 5, "baseWeight": 0.58, "spawnTier": 8, "shapeClass": "Crystal", "hardnessMultiplier": 1.2, "armorBias": 0.45, "resistBias": 0.08, "enemyCommonDrop": false, "id": "PhaseQuartz"},
  echoResin: {"name": "Résine", "cargoPerUnit": 1, "sellPrice": 34, "colorHex": "#2e8b57", "rarity": 3, "baseWeight": 0.9, "spawnTier": 4, "shapeClass": "Biomass", "hardnessMultiplier": 0.95, "armorBias": 0.0, "resistBias": 0.03, "enemyCommonDrop": false, "id": "EchoResin"},
  stellarAsh: {"name": "Cendre volcanique", "cargoPerUnit": 1, "sellPrice": 34, "colorHex": "#778899", "rarity": 3, "baseWeight": 0.95, "spawnTier": 4, "shapeClass": "Dust", "hardnessMultiplier": 0.9, "armorBias": -0.2, "resistBias": -0.02, "enemyCommonDrop": false, "id": "StellarAsh"},
  gravitonFilament: {"name": "Tungstène filé", "cargoPerUnit": 1, "sellPrice": 88, "colorHex": "#87cefa", "rarity": 6, "baseWeight": 0.32, "spawnTier": 10, "shapeClass": "Exotic", "hardnessMultiplier": 1.23, "armorBias": 0.75, "resistBias": 0.1, "enemyCommonDrop": false, "id": "GravitonFilament"},
  chronoShard: {"name": "Zircone", "cargoPerUnit": 1, "sellPrice": 88, "colorHex": "#ffe4b5", "rarity": 6, "baseWeight": 0.31, "spawnTier": 10, "shapeClass": "Crystal", "hardnessMultiplier": 1.24, "armorBias": 0.8, "resistBias": 0.1, "enemyCommonDrop": false, "id": "ChronoShard"},
  prismTear: {"name": "Fluorite", "cargoPerUnit": 1, "sellPrice": 91, "colorHex": "#ff00ff", "rarity": 6, "baseWeight": 0.27, "spawnTier": 11, "shapeClass": "Crystal", "hardnessMultiplier": 1.28, "armorBias": 0.85, "resistBias": 0.11, "enemyCommonDrop": false, "id": "PrismTear"},
  singularitySeed: {"name": "Silicium monocristallin", "cargoPerUnit": 1, "sellPrice": 116, "colorHex": "#000000", "rarity": 7, "baseWeight": 0.12, "spawnTier": 14, "shapeClass": "Exotic", "hardnessMultiplier": 1.45, "armorBias": 1.25, "resistBias": 0.16, "enemyCommonDrop": false, "id": "SingularitySeed"},
  aetherFoam: {"name": "Aérogel de silice", "cargoPerUnit": 1, "sellPrice": 91, "colorHex": "#f0ffff", "rarity": 6, "baseWeight": 0.27, "spawnTier": 11, "shapeClass": "Exotic", "hardnessMultiplier": 1.18, "armorBias": 0.45, "resistBias": 0.11, "enemyCommonDrop": false, "id": "AetherFoam"},
  nullGlass: {"name": "Obsidienne", "cargoPerUnit": 1, "sellPrice": 71, "colorHex": "#9400d3", "rarity": 5, "baseWeight": 0.45, "spawnTier": 9, "shapeClass": "Crystal", "hardnessMultiplier": 1.3, "armorBias": 1.1, "resistBias": 0.1, "enemyCommonDrop": false, "id": "NullGlass"},
  basaltChunk: {"name": "Basalte", "cargoPerUnit": 1, "sellPrice": 40, "colorHex": "#5c5c60", "rarity": 1, "baseWeight": 1.1, "spawnTier": 1, "shapeClass": "Rock", "hardnessMultiplier": 1.02, "armorBias": 0.3, "resistBias": 0.01, "enemyCommonDrop": true, "id": "BasaltChunk"},
  manganeseNodule: {"name": "Concrétion manganésifère", "cargoPerUnit": 1, "sellPrice": 40, "colorHex": "#866a5d", "rarity": 2, "baseWeight": 1.0, "spawnTier": 2, "shapeClass": "Rock", "hardnessMultiplier": 1.05, "armorBias": 0.25, "resistBias": 0.01, "enemyCommonDrop": true, "id": "ManganeseNodule"},
  boronFlake: {"name": "Borax", "cargoPerUnit": 1, "sellPrice": 40, "colorHex": "#ffd68c", "rarity": 2, "baseWeight": 0.9, "spawnTier": 3, "shapeClass": "Crystal", "hardnessMultiplier": 1.02, "armorBias": 0.1, "resistBias": 0.02, "enemyCommonDrop": false, "id": "BoronFlake"},
  phosphorite: {"name": "Phosphorite", "cargoPerUnit": 1, "sellPrice": 40, "colorHex": "#d7d49c", "rarity": 2, "baseWeight": 0.95, "spawnTier": 2, "shapeClass": "Rock", "hardnessMultiplier": 0.95, "armorBias": 0.0, "resistBias": 0.0, "enemyCommonDrop": false, "id": "Phosphorite"},
  sodiumClathrate: {"name": "Natron", "cargoPerUnit": 1, "sellPrice": 40, "colorHex": "#d2e9ff", "rarity": 2, "baseWeight": 0.95, "spawnTier": 3, "shapeClass": "Ice", "hardnessMultiplier": 0.86, "armorBias": -0.35, "resistBias": -0.03, "enemyCommonDrop": false, "id": "SodiumClathrate"},
  argonIce: {"name": "Argon solide", "cargoPerUnit": 1, "sellPrice": 40, "colorHex": "#c6f0ff", "rarity": 2, "baseWeight": 0.85, "spawnTier": 3, "shapeClass": "Ice", "hardnessMultiplier": 0.84, "armorBias": -0.45, "resistBias": -0.04, "enemyCommonDrop": false, "id": "ArgonIce"},
  ceresClay: {"name": "Argile", "cargoPerUnit": 1, "sellPrice": 40, "colorHex": "#aa876c", "rarity": 1, "baseWeight": 1.05, "spawnTier": 1, "shapeClass": "Dust", "hardnessMultiplier": 0.88, "armorBias": -0.2, "resistBias": -0.01, "enemyCommonDrop": true, "id": "CeresClay"},
  grapheneVeil: {"name": "Graphène", "cargoPerUnit": 1, "sellPrice": 40, "colorHex": "#464655", "rarity": 3, "baseWeight": 0.85, "spawnTier": 5, "shapeClass": "Junk", "hardnessMultiplier": 1.05, "armorBias": 0.25, "resistBias": 0.03, "enemyCommonDrop": true, "id": "GrapheneVeil"},
  tungstenOre: {"name": "Minerai de tungstène", "cargoPerUnit": 1, "sellPrice": 40, "colorHex": "#82919b", "rarity": 3, "baseWeight": 0.75, "spawnTier": 5, "shapeClass": "Rock", "hardnessMultiplier": 1.18, "armorBias": 0.65, "resistBias": 0.04, "enemyCommonDrop": false, "id": "TungstenOre"},
  rutileShard: {"name": "Rutile", "cargoPerUnit": 1, "sellPrice": 40, "colorHex": "#cdaa78", "rarity": 3, "baseWeight": 0.8, "spawnTier": 5, "shapeClass": "Crystal", "hardnessMultiplier": 1.08, "armorBias": 0.25, "resistBias": 0.04, "enemyCommonDrop": false, "id": "RutileShard"},
  galliumBloom: {"name": "Gallium", "cargoPerUnit": 1, "sellPrice": 40, "colorHex": "#aebfff", "rarity": 4, "baseWeight": 0.78, "spawnTier": 6, "shapeClass": "Crystal", "hardnessMultiplier": 1.03, "armorBias": 0.2, "resistBias": 0.04, "enemyCommonDrop": false, "id": "GalliumBloom"},
  seleniumThread: {"name": "Sélénium", "cargoPerUnit": 1, "sellPrice": 40, "colorHex": "#ffbc78", "rarity": 4, "baseWeight": 0.78, "spawnTier": 6, "shapeClass": "Junk", "hardnessMultiplier": 1.04, "armorBias": 0.2, "resistBias": 0.04, "enemyCommonDrop": false, "id": "SeleniumThread"},
  hafniumPlate: {"name": "Plaque d'hafnium", "cargoPerUnit": 1, "sellPrice": 40, "colorHex": "#97a6b4", "rarity": 4, "baseWeight": 0.6, "spawnTier": 7, "shapeClass": "Junk", "hardnessMultiplier": 1.16, "armorBias": 0.75, "resistBias": 0.04, "enemyCommonDrop": false, "id": "HafniumPlate"},
  rutheniumDust: {"name": "Ruthénium", "cargoPerUnit": 1, "sellPrice": 40, "colorHex": "#b4bcc0", "rarity": 4, "baseWeight": 0.62, "spawnTier": 7, "shapeClass": "Dust", "hardnessMultiplier": 1.08, "armorBias": 0.45, "resistBias": 0.04, "enemyCommonDrop": false, "id": "RutheniumDust"},
  telluricGlass: {"name": "Tellure", "cargoPerUnit": 1, "sellPrice": 40, "colorHex": "#76e1cd", "rarity": 5, "baseWeight": 0.55, "spawnTier": 8, "shapeClass": "Crystal", "hardnessMultiplier": 1.16, "armorBias": 0.55, "resistBias": 0.07, "enemyCommonDrop": false, "id": "TelluricGlass"},
  mercuryIce: {"name": "Mercure", "cargoPerUnit": 1, "sellPrice": 40, "colorHex": "#d6e0ea", "rarity": 5, "baseWeight": 0.52, "spawnTier": 8, "shapeClass": "Ice", "hardnessMultiplier": 1.03, "armorBias": 0.1, "resistBias": 0.05, "enemyCommonDrop": false, "id": "MercuryIce"},
  cesiumSalt: {"name": "Formiate de césium", "cargoPerUnit": 1, "sellPrice": 40, "colorHex": "#ece1ff", "rarity": 4, "baseWeight": 0.62, "spawnTier": 7, "shapeClass": "Dust", "hardnessMultiplier": 0.95, "armorBias": 0.1, "resistBias": 0.04, "enemyCommonDrop": false, "id": "CesiumSalt"},
  lanthanumKnot: {"name": "Monazite", "cargoPerUnit": 1, "sellPrice": 40, "colorHex": "#ace8d6", "rarity": 5, "baseWeight": 0.5, "spawnTier": 8, "shapeClass": "Exotic", "hardnessMultiplier": 1.08, "armorBias": 0.3, "resistBias": 0.07, "enemyCommonDrop": false, "id": "LanthanumKnot"},
  yttriumPrism: {"name": "Xénotime", "cargoPerUnit": 1, "sellPrice": 40, "colorHex": "#c4faff", "rarity": 5, "baseWeight": 0.44, "spawnTier": 9, "shapeClass": "Crystal", "hardnessMultiplier": 1.18, "armorBias": 0.45, "resistBias": 0.08, "enemyCommonDrop": false, "id": "YttriumPrism"},
  zirconCore: {"name": "Zircon", "cargoPerUnit": 1, "sellPrice": 40, "colorHex": "#ebf2ff", "rarity": 5, "baseWeight": 0.42, "spawnTier": 9, "shapeClass": "Crystal", "hardnessMultiplier": 1.18, "armorBias": 0.55, "resistBias": 0.08, "enemyCommonDrop": false, "id": "ZirconCore"},
  quasarPollen: {"name": "Soufre sublimé", "cargoPerUnit": 1, "sellPrice": 40, "colorHex": "#fff596", "rarity": 6, "baseWeight": 0.25, "spawnTier": 11, "shapeClass": "Dust", "hardnessMultiplier": 1.15, "armorBias": 0.6, "resistBias": 0.11, "enemyCommonDrop": false, "id": "QuasarPollen"},
  eventidePearl: {"name": "Opale noire", "cargoPerUnit": 1, "sellPrice": 40, "colorHex": "#d2b4ff", "rarity": 6, "baseWeight": 0.22, "spawnTier": 12, "shapeClass": "Crystal", "hardnessMultiplier": 1.25, "armorBias": 0.9, "resistBias": 0.12, "enemyCommonDrop": false, "id": "EventidePearl"},
  vacuumLotus: {"name": "Kelp séché", "cargoPerUnit": 1, "sellPrice": 40, "colorHex": "#affff0", "rarity": 6, "baseWeight": 0.2, "spawnTier": 12, "shapeClass": "Biomass", "hardnessMultiplier": 1.12, "armorBias": 0.45, "resistBias": 0.12, "enemyCommonDrop": false, "id": "VacuumLotus"},
  entropySpore: {"name": "Spores fongiques", "cargoPerUnit": 1, "sellPrice": 40, "colorHex": "#82ffa0", "rarity": 7, "baseWeight": 0.16, "spawnTier": 13, "shapeClass": "Biomass", "hardnessMultiplier": 1.28, "armorBias": 0.95, "resistBias": 0.14, "enemyCommonDrop": false, "id": "EntropySpore"},
  lumenMoss: {"name": "Lichen", "cargoPerUnit": 1, "sellPrice": 40, "colorHex": "#98ff7c", "rarity": 3, "baseWeight": 0.78, "spawnTier": 5, "shapeClass": "Biomass", "hardnessMultiplier": 0.9, "armorBias": -0.1, "resistBias": 0.03, "enemyCommonDrop": false, "id": "LumenMoss"},
  magnetarSkin: {"name": "Magnétite", "cargoPerUnit": 1, "sellPrice": 40, "colorHex": "#6eaaff", "rarity": 7, "baseWeight": 0.06, "spawnTier": 16, "shapeClass": "Exotic", "hardnessMultiplier": 1.55, "armorBias": 1.35, "resistBias": 0.17, "enemyCommonDrop": false, "id": "MagnetarSkin"},
};

export function getResourceRarityScore(key){ return RESOURCE_DEFS[key]?.rarity ?? 1; }
export function getResourceDef(key){ return RESOURCE_DEFS[key] || null; }
export function isKnownResource(key){ return !!RESOURCE_DEFS[key]; }
