export const STATUS_EFFECT_FLAGS = Object.freeze({
  NONE: 0,
  PERSISTENT: 1 << 0,
  BUFF: 1 << 1,
  DEBUFF: 1 << 2,
  CLEANSEABLE: 1 << 3,
  REDUCED_BY_TENACITY: 1 << 4,
  BLOCKED_BY_SPELL_SHIELD: 1 << 5,
  BREAK_ON_EXTERNAL_HIT: 1 << 6,
  HIDDEN_FROM_WORLD_ICON: 1 << 7,
  HIDDEN_FROM_HUD_ICON: 1 << 8,
  SUPPORTS_STACKS: 1 << 9
});
