export const BASE_TILE_SIZE = 64;

export const STRUCTURE_TYPES = {
  BASE_CORE: 'base_core',
  WALL: 'wall',
  DOOR: 'door',
  STORAGE: 'storage',
  EQUIPMENT_STORAGE: 'equipment_storage',
  AMMO_STORAGE: 'ammo_storage',
  SOLAR_PANEL: 'solar_panel',
  FUEL_GENERATOR: 'fuel_generator',
  FUEL_TANK: 'fuel_tank',
  FURNACE: 'furnace',
  HIGH_TEMP_FURNACE: 'high_temp_furnace',
  CHEMICAL_REFINERY: 'chemical_refinery',
  ELECTROLYZER: 'electrolyzer',
  ELECTRONICS_BENCH: 'electronics_bench',
  INDUSTRIAL_PRESS: 'industrial_press',
  SCIENCE_LAB: 'science_lab',
  INDUSTRIAL_CONVERTER: 'industrial_converter',
  ROCKET_WORKSHOP: 'rocket_workshop',
  RESEARCH_STATION: 'research_station',
  EQUIPMENT_FABRICATOR: 'equipment_fabricator',
  EQUIPMENT_RD_STATION: 'equipment_rd_station',
  RESOURCE_DEPOSIT: 'resource_deposit',
  MINING_EXTRACTOR: 'mining_extractor',
  CONVEYOR: 'conveyor',
  FAST_CONVEYOR: 'fast_conveyor',
  SPLITTER: 'splitter',
  MERGER: 'merger',
  ROBOT_ARM: 'robot_arm',
  FAST_ARM: 'fast_arm',
  LONG_ARM: 'long_arm'
};

export const STRUCTURE_DEFS = {
  [STRUCTURE_TYPES.BASE_CORE]: {
    id: STRUCTURE_TYPES.BASE_CORE,
    name: 'Noyau de base',
    description: 'Définit une zone de construction personnelle tier 1.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 1200,
    solid: false,
    claimRadius: BASE_TILE_SIZE * 8,
    maxPerOwner: 1,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    color: '#244e68',
    borderColor: '#8de7ff',
    cost: { scrap: 20, ironOre: 12, copper: 6 }
  },
  [STRUCTURE_TYPES.WALL]: {
    id: STRUCTURE_TYPES.WALL,
    name: 'Mur métallique',
    description: 'Mur solide 3 × 1.',
    radius: 96,
    tilesX: 3,
    tilesY: 1,
    w: BASE_TILE_SIZE * 3,
    h: BASE_TILE_SIZE,
    maxHp: 760,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: true,
    color: '#263748',
    borderColor: '#73d4ff',
    cost: { scrap: 8, ironOre: 6 }
  },
  [STRUCTURE_TYPES.DOOR]: {
    id: STRUCTURE_TYPES.DOOR,
    name: 'Porte renforcée',
    description: 'Porte 3 × 1 ouvrable par le propriétaire.',
    radius: 96,
    tilesX: 3,
    tilesY: 1,
    w: BASE_TILE_SIZE * 3,
    h: BASE_TILE_SIZE,
    maxHp: 680,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: true,
    openable: true,
    color: '#334454',
    borderColor: '#87d9ff',
    cost: { scrap: 6, ironOre: 8, copper: 3 }
  },
  [STRUCTURE_TYPES.STORAGE]: {
    id: STRUCTURE_TYPES.STORAGE,
    name: 'Coffre de ressources',
    description: 'Stockage local de ressources.',
    radius: 32,
    tilesX: 1,
    tilesY: 1,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    storageKind: 'resources',
    storageSlots: 12,
    storageCapacity: 420,
    color: '#30544b',
    borderColor: '#70f0c5',
    cost: { scrap: 10, ironOre: 8, copper: 4 }
  },
  [STRUCTURE_TYPES.EQUIPMENT_STORAGE]: {
    id: STRUCTURE_TYPES.EQUIPMENT_STORAGE,
    name: 'Coffre d’équipement',
    description: 'Stockage local pour armes, lance-roquettes et modules.',
    radius: 32,
    tilesX: 1,
    tilesY: 1,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    storageKind: 'equipment',
    itemCapacity: 18,
    color: '#30425e',
    borderColor: '#8bb8ff',
    cost: { ironIngot: 4, copperWire: 4, scrap: 8 }
  },
  [STRUCTURE_TYPES.SOLAR_PANEL]: {
    id: STRUCTURE_TYPES.SOLAR_PANEL,
    name: 'Panneau solaire',
    description: 'Produit une énergie faible mais gratuite.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    energyOutput: 8,
    color: '#3f594f',
    borderColor: '#bde992',
    cost: { silicon: 8, copper: 6, ironOre: 6 }
  },
  [STRUCTURE_TYPES.FUEL_GENERATOR]: {
    id: STRUCTURE_TYPES.FUEL_GENERATOR,
    name: 'Générateur thermique',
    description: 'Produit beaucoup d’énergie en consommant du carburant.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    storageKind: 'fuel',
    fuelCapacity: 80,
    energyOutput: 34,
    fuelUsePerSecond: 0.025,
    color: '#5d4632',
    borderColor: '#ffb761',
    cost: { ironIngot: 4, copperWire: 4, steelPlate: 2 }
  },
  [STRUCTURE_TYPES.FUEL_TANK]: {
    id: STRUCTURE_TYPES.FUEL_TANK,
    name: 'Réservoir de carburant',
    description: 'Stocke le carburant de la base.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    storageKind: 'fuel',
    fuelCapacity: 240,
    color: '#5b4932',
    borderColor: '#ffc36f',
    cost: { ironIngot: 4, copperWire: 2, steelPlate: 1 }
  }
,
  [STRUCTURE_TYPES.AMMO_STORAGE]: {
    id: STRUCTURE_TYPES.AMMO_STORAGE,
    name: 'Coffre de roquettes',
    description: 'Stockage local pour munitions de lance-roquettes.',
    radius: 32,
    tilesX: 1,
    tilesY: 1,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    storageKind: 'ammo',
    ammoCapacity: 260,
    color: '#5a4030',
    borderColor: '#ffc16f',
    cost: { steelPlate: 2, copperWire: 4 }
  }
,
  [STRUCTURE_TYPES.FURNACE]: {
    id: STRUCTURE_TYPES.FURNACE,
    name: 'Four basique',
    description: 'Fonte simple des minerais communs.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    machineType: 'furnace',
    energyUse: 4,
    color: '#4a3e35',
    borderColor: '#ffb36b',
    cost: { scrap: 8, ironOre: 12, copper: 3 }
  },
  [STRUCTURE_TYPES.HIGH_TEMP_FURNACE]: {
    id: STRUCTURE_TYPES.HIGH_TEMP_FURNACE,
    name: 'Four haute température',
    description: 'Traitement thermique avancé.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    machineType: 'high_temp_furnace',
    energyUse: 9,
    color: '#503833',
    borderColor: '#ff7d5f',
    cost: { ironIngot: 6, copperIngot: 4, graphite: 6 }
  },
  [STRUCTURE_TYPES.CHEMICAL_REFINERY]: {
    id: STRUCTURE_TYPES.CHEMICAL_REFINERY,
    name: 'Raffinerie chimique',
    description: 'Transforme hydrocarbures et matières organiques.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    machineType: 'chemical_refinery',
    energyUse: 6,
    color: '#3d4d3d',
    borderColor: '#95df89',
    cost: { steelPlate: 2, copperWire: 4, silicon: 4 }
  },
  [STRUCTURE_TYPES.ELECTROLYZER]: {
    id: STRUCTURE_TYPES.ELECTROLYZER,
    name: 'Électrolyseur',
    description: 'Sépare et stabilise les volatils.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    machineType: 'electrolyzer',
    energyUse: 8,
    color: '#344f5a',
    borderColor: '#84ddff',
    cost: { steelPlate: 2, copperWire: 6, silicon: 6 }
  },
  [STRUCTURE_TYPES.ELECTRONICS_BENCH]: {
    id: STRUCTURE_TYPES.ELECTRONICS_BENCH,
    name: 'Atelier électronique',
    description: 'Produit wafers, transistors et circuits.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    machineType: 'electronics_bench',
    energyUse: 7,
    color: '#313f5a',
    borderColor: '#8bb8ff',
    cost: { steelPlate: 3, copperWire: 8, silicon: 10 }
  },
  [STRUCTURE_TYPES.SCIENCE_LAB]: {
    id: STRUCTURE_TYPES.SCIENCE_LAB,
    name: 'Laboratoire scientifique',
    description: 'Fabrique des packs de science à partir de composants industriels.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    machineType: 'science_lab',
    energyUse: 6,
    color: '#25384d',
    borderColor: '#7edcff',
    cost: { ironOre: 16, copper: 8, silicon: 6 }
  },


  [STRUCTURE_TYPES.INDUSTRIAL_CONVERTER]: {
    id: STRUCTURE_TYPES.INDUSTRIAL_CONVERTER,
    name: 'Convertisseur industriel',
    description: 'Convertit des ressources via des recettes achetées dans les stations pirates.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    machineType: 'industrial_converter',
    energyUse: 10,
    color: '#3d3048',
    borderColor: '#ff8ce6',
    cost: { steelPlate: 6, copperWire: 10, controlCircuit: 2, titaniumPlate: 1 }
  },


  [STRUCTURE_TYPES.ROCKET_WORKSHOP]: {
    id: STRUCTURE_TYPES.ROCKET_WORKSHOP,
    name: 'Atelier de roquettes',
    description: 'Produit des lots de roquettes à partir de composants industriels.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    rocketWorkshop: true,
    energyUse: 12,
    color: '#4a3828',
    borderColor: '#ffb85c',
    cost: { steelPlate: 5, propellant: 5, controlCircuit: 1 }
  },

  [STRUCTURE_TYPES.RESEARCH_STATION]: {
    id: STRUCTURE_TYPES.RESEARCH_STATION,
    name: 'Station de recherche',
    description: 'Consomme des packs de science pour débloquer des technologies.',
    radius: 72,
    tilesX: 3,
    tilesY: 2,
    w: BASE_TILE_SIZE * 3,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    researchStation: true,
    energyUse: 8,
    color: '#26304d',
    borderColor: '#b58cff',
    cost: { ironIngot: 4, copper: 10, silicon: 6 }
  },

  [STRUCTURE_TYPES.INDUSTRIAL_PRESS]: {
    id: STRUCTURE_TYPES.INDUSTRIAL_PRESS,
    name: 'Presse industrielle',
    description: 'Assemble plaques et composants mécaniques.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    machineType: 'industrial_press',
    energyUse: 10,
    color: '#3e4653',
    borderColor: '#b6c8dc',
    cost: { ironIngot: 4, copper: 8, graphite: 4 }
  }
,

[STRUCTURE_TYPES.RESOURCE_DEPOSIT]: {
  id: STRUCTURE_TYPES.RESOURCE_DEPOSIT,
  name: 'Gisement',
  description: 'Source permanente exploitable par extracteur.',
  radius: 58,
  tilesX: 2,
  tilesY: 2,
  w: BASE_TILE_SIZE * 2,
  h: BASE_TILE_SIZE * 2,
  maxHp: 0,
  damageable: false,
  buildRange: 1100,
  gridSize: BASE_TILE_SIZE,
  solid: false,
  neutral: true,
  mineable: true,
  infiniteDeposit: true,
  color: '#334a45',
  borderColor: '#9ef0c7',
  cost: {}
},

[STRUCTURE_TYPES.MINING_EXTRACTOR]: {
  id: STRUCTURE_TYPES.MINING_EXTRACTOR,
  name: 'Extracteur minier',
  description: 'Fore une source permanente. Débit limité par le cycle, le buffer et l’énergie.',
  radius: 48,
  tilesX: 2,
  tilesY: 2,
  w: BASE_TILE_SIZE * 2,
  h: BASE_TILE_SIZE * 2,
  maxHp: 0,
  damageable: false,
  buildRange: 1100,
  gridSize: BASE_TILE_SIZE,
  solid: false,
  rotatable: true,
  storageKind: 'conveyor',
  storageCapacity: 8,
  automationKind: 'extractor',
  extractionIntervalMs: 2200,
  extractionRange: BASE_TILE_SIZE * 2.6,
  extractionYield: 1,
  energyUse: 18,
  color: '#314759',
  borderColor: '#9fdcff',
  cost: { steelPlate: 4, copperWire: 8, controlCircuit: 1 }
},

  [STRUCTURE_TYPES.CONVEYOR]: {
    id: STRUCTURE_TYPES.CONVEYOR,
    name: 'Convoyeur',
    description: 'Transporte automatiquement les ressources dans son sens.',
    radius: 32,
    tilesX: 1,
    tilesY: 1,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    rotatable: false,
    storageKind: 'conveyor',
    storageCapacity: 1,
    automationKind: 'conveyor',
    automationIntervalMs: 720,
    automationOutputs: ['front'],
    color: '#253f4a',
    borderColor: '#6ed7ff',
    cost: { ironOre: 6, copper: 2 }
  },
  [STRUCTURE_TYPES.FAST_CONVEYOR]: {
    id: STRUCTURE_TYPES.FAST_CONVEYOR,
    name: 'Convoyeur rapide',
    description: 'Convoyeur industriel plus rapide.',
    radius: 32,
    tilesX: 1,
    tilesY: 1,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    rotatable: false,
    storageKind: 'conveyor',
    storageCapacity: 1,
    automationKind: 'conveyor',
    automationIntervalMs: 420,
    automationOutputs: ['front'],
    color: '#213f57',
    borderColor: '#79f1ff',
    cost: { ironIngot: 2, copperWire: 2 }
  },

  [STRUCTURE_TYPES.SPLITTER]: {
    id: STRUCTURE_TYPES.SPLITTER,
    name: 'Répartiteur',
    description: 'Une entrée, deux sorties.',
    radius: 48,
    tilesX: 1,
    tilesY: 2,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    rotatable: false,
    storageKind: 'conveyor',
    storageCapacity: 1,
    automationKind: 'conveyor',
    automationIntervalMs: 760,
    automationOutputs: ['upper', 'lower'],
    color: '#263f55',
    borderColor: '#a2ebff',
    cost: { ironIngot: 3, copperWire: 2 }
  },


  [STRUCTURE_TYPES.MERGER]: {
    id: STRUCTURE_TYPES.MERGER,
    name: 'Fusionneur',
    description: 'Deux entrées, une sortie.',
    radius: 48,
    tilesX: 1,
    tilesY: 2,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    rotatable: false,
    storageKind: 'conveyor',
    storageCapacity: 1,
    automationKind: 'conveyor',
    automationIntervalMs: 700,
    automationOutputs: ['upper'],
    color: '#2a3f50',
    borderColor: '#ffd98a',
    cost: { ironIngot: 3, copperWire: 2 }
  },

  [STRUCTURE_TYPES.ROBOT_ARM]: {
    id: STRUCTURE_TYPES.ROBOT_ARM,
    name: 'Bras robotique',
    description: 'Déplace les ressources entre coffre, machine et convoyeur.',
    radius: 32,
    tilesX: 1,
    tilesY: 1,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    rotatable: true,
    automationKind: 'robot_arm',
    automationIntervalMs: 920,
    automationReachTiles: 1,
    color: '#443a2c',
    borderColor: '#ffd27b',
    cost: { ironIngot: 2, copperWire: 2 }
  },
  [STRUCTURE_TYPES.FAST_ARM]: {
    id: STRUCTURE_TYPES.FAST_ARM,
    name: 'Bras rapide',
    description: 'Bras robotique à cycle court.',
    radius: 32,
    tilesX: 1,
    tilesY: 1,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    rotatable: true,
    automationKind: 'robot_arm',
    automationIntervalMs: 560,
    automationReachTiles: 1,
    color: '#4d3c25',
    borderColor: '#ffe08a',
    cost: { steelPlate: 1, copperWire: 3 }
  },
  [STRUCTURE_TYPES.LONG_ARM]: {
    id: STRUCTURE_TYPES.LONG_ARM,
    name: 'Bras long',
    description: 'Bras robotique capable de franchir deux cases.',
    radius: 32,
    tilesX: 1,
    tilesY: 1,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    rotatable: true,
    automationKind: 'robot_arm',
    automationIntervalMs: 1150,
    automationReachTiles: 2,
    color: '#4b3a2b',
    borderColor: '#ffc86e',
    cost: { steelPlate: 1, copperWire: 3 }
  }
,
  [STRUCTURE_TYPES.EQUIPMENT_FABRICATOR]: {
    id: STRUCTURE_TYPES.EQUIPMENT_FABRICATOR,
    name: 'Atelier d’équipement',
    description: 'Fabrique des armes, boucliers, propulseurs et modules à partir de composants avancés.',
    radius: 64,
    tilesX: 3,
    tilesY: 2,
    w: BASE_TILE_SIZE * 3,
    h: BASE_TILE_SIZE * 2,
    maxHp: 420,
    solid: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    color: '#26324f',
    borderColor: '#b58cff',
    energyUse: 18,
    cost: { steelPlate: 8, microprocessor: 2, controlCircuit: 2, advancedSciencePack: 1 }
  }
,
  [STRUCTURE_TYPES.EQUIPMENT_RD_STATION]: {
    id: STRUCTURE_TYPES.EQUIPMENT_RD_STATION,
    name: 'Station R&D',
    description: 'Améliore un objet neutre avec 1 à 3 sciences pour générer des stats, passifs et tags procéduraux.',
    radius: 64,
    tilesX: 3,
    tilesY: 2,
    w: BASE_TILE_SIZE * 3,
    h: BASE_TILE_SIZE * 2,
    maxHp: 420,
    solid: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    color: '#2e244f',
    borderColor: '#d28cff',
    energyUse: 24,
    cost: { steelPlate: 10, microprocessor: 3, controlCircuit: 3, advancedSciencePack: 2 }
  }


};

export function getStructureDef(type) {
  return STRUCTURE_DEFS[String(type || '').toLowerCase()] || null;
}

export function getStructureBuildCost(type) {
  return { ...(getStructureDef(type)?.cost || {}) };
}
