export const BASE_TILE_SIZE = 64;

export const STRUCTURE_TYPES = {
  BASE_CORE: 'base_core',
  WALL: 'wall',
  DOOR: 'door',
  STORAGE: 'storage',
  EQUIPMENT_STORAGE: 'equipment_storage',
  AMMO_STORAGE: 'ammo_storage',
  SOLAR_PANEL: 'solar_panel',
  FUEL_GENERATOR: 'fuel_generator',
  FUEL_TANK: 'fuel_tank',
  FURNACE: 'furnace',
  HIGH_TEMP_FURNACE: 'high_temp_furnace',
  CHEMICAL_REFINERY: 'chemical_refinery',
  ELECTROLYZER: 'electrolyzer',
  ELECTRONICS_BENCH: 'electronics_bench',
  INDUSTRIAL_PRESS: 'industrial_press',
  CONVEYOR: 'conveyor',
  FAST_CONVEYOR: 'fast_conveyor',
  SPLITTER: 'splitter',
  MERGER: 'merger',
  ROBOT_ARM: 'robot_arm',
  FAST_ARM: 'fast_arm',
  LONG_ARM: 'long_arm'
};

export const STRUCTURE_DEFS = {
  [STRUCTURE_TYPES.BASE_CORE]: {
    id: STRUCTURE_TYPES.BASE_CORE,
    name: 'Noyau de base',
    description: 'Définit une zone de construction personnelle tier 1.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 1200,
    solid: false,
    claimRadius: BASE_TILE_SIZE * 8,
    maxPerOwner: 1,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    color: '#244e68',
    borderColor: '#8de7ff',
    cost: { ironOre: 35, copper: 12, aluminiumOre: 8 }
  },
  [STRUCTURE_TYPES.WALL]: {
    id: STRUCTURE_TYPES.WALL,
    name: 'Mur métallique',
    description: 'Mur solide 3 × 1.',
    radius: 96,
    tilesX: 3,
    tilesY: 1,
    w: BASE_TILE_SIZE * 3,
    h: BASE_TILE_SIZE,
    maxHp: 760,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: true,
    color: '#263748',
    borderColor: '#73d4ff',
    cost: { ironOre: 12, copper: 2 }
  },
  [STRUCTURE_TYPES.DOOR]: {
    id: STRUCTURE_TYPES.DOOR,
    name: 'Porte renforcée',
    description: 'Porte 3 × 1 ouvrable par le propriétaire.',
    radius: 96,
    tilesX: 3,
    tilesY: 1,
    w: BASE_TILE_SIZE * 3,
    h: BASE_TILE_SIZE,
    maxHp: 680,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: true,
    openable: true,
    color: '#334454',
    borderColor: '#87d9ff',
    cost: { ironOre: 10, copper: 4, aluminiumOre: 2 }
  },
  [STRUCTURE_TYPES.STORAGE]: {
    id: STRUCTURE_TYPES.STORAGE,
    name: 'Coffre de ressources',
    description: 'Stockage local de ressources.',
    radius: 32,
    tilesX: 1,
    tilesY: 1,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    storageKind: 'resources',
    storageSlots: 12,
    storageCapacity: 420,
    color: '#30544b',
    borderColor: '#70f0c5',
    cost: { ironOre: 14, copper: 8, aluminiumOre: 4 }
  },
  [STRUCTURE_TYPES.EQUIPMENT_STORAGE]: {
    id: STRUCTURE_TYPES.EQUIPMENT_STORAGE,
    name: 'Coffre d’équipement',
    description: 'Stockage local pour armes, lance-roquettes et modules.',
    radius: 32,
    tilesX: 1,
    tilesY: 1,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    storageKind: 'equipment',
    itemCapacity: 18,
    color: '#30425e',
    borderColor: '#8bb8ff',
    cost: { ironOre: 18, copper: 10, aluminiumOre: 8 }
  },
  [STRUCTURE_TYPES.SOLAR_PANEL]: {
    id: STRUCTURE_TYPES.SOLAR_PANEL,
    name: 'Panneau solaire',
    description: 'Produit une énergie faible mais gratuite.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    energyOutput: 8,
    color: '#3f594f',
    borderColor: '#bde992',
    cost: { silicon: 12, copper: 8, aluminiumOre: 8 }
  },
  [STRUCTURE_TYPES.FUEL_GENERATOR]: {
    id: STRUCTURE_TYPES.FUEL_GENERATOR,
    name: 'Générateur thermique',
    description: 'Produit beaucoup d’énergie en consommant du carburant.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    storageKind: 'fuel',
    fuelCapacity: 80,
    energyOutput: 34,
    fuelUsePerSecond: 0.025,
    color: '#5d4632',
    borderColor: '#ffb761',
    cost: { ironOre: 18, copper: 10, aluminiumOre: 8 }
  },
  [STRUCTURE_TYPES.FUEL_TANK]: {
    id: STRUCTURE_TYPES.FUEL_TANK,
    name: 'Réservoir de carburant',
    description: 'Stocke le carburant de la base.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    storageKind: 'fuel',
    fuelCapacity: 240,
    color: '#5b4932',
    borderColor: '#ffc36f',
    cost: { ironOre: 16, copper: 8, aluminiumOre: 8 }
  }
,
  [STRUCTURE_TYPES.AMMO_STORAGE]: {
    id: STRUCTURE_TYPES.AMMO_STORAGE,
    name: 'Coffre de roquettes',
    description: 'Stockage local pour munitions de lance-roquettes.',
    radius: 32,
    tilesX: 1,
    tilesY: 1,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    storageKind: 'ammo',
    ammoCapacity: 260,
    color: '#5a4030',
    borderColor: '#ffc16f',
    cost: { ironOre: 16, copper: 6, aluminiumOre: 6 }
  }
,
  [STRUCTURE_TYPES.FURNACE]: {
    id: STRUCTURE_TYPES.FURNACE,
    name: 'Four basique',
    description: 'Fonte simple des minerais communs.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    machineType: 'furnace',
    energyUse: 4,
    color: '#4a3e35',
    borderColor: '#ffb36b',
    cost: { ironOre: 18, copper: 4 }
  },
  [STRUCTURE_TYPES.HIGH_TEMP_FURNACE]: {
    id: STRUCTURE_TYPES.HIGH_TEMP_FURNACE,
    name: 'Four haute température',
    description: 'Traitement thermique avancé.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    machineType: 'high_temp_furnace',
    energyUse: 9,
    color: '#503833',
    borderColor: '#ff7d5f',
    cost: { steelPlate: 4, copper: 8, aluminiumOre: 8 }
  },
  [STRUCTURE_TYPES.CHEMICAL_REFINERY]: {
    id: STRUCTURE_TYPES.CHEMICAL_REFINERY,
    name: 'Raffinerie chimique',
    description: 'Transforme hydrocarbures et matières organiques.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    machineType: 'chemical_refinery',
    energyUse: 6,
    color: '#3d4d3d',
    borderColor: '#95df89',
    cost: { ironOre: 18, copper: 8, aluminiumOre: 6 }
  },
  [STRUCTURE_TYPES.ELECTROLYZER]: {
    id: STRUCTURE_TYPES.ELECTROLYZER,
    name: 'Électrolyseur',
    description: 'Sépare et stabilise les volatils.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    machineType: 'electrolyzer',
    energyUse: 8,
    color: '#344f5a',
    borderColor: '#84ddff',
    cost: { aluminiumOre: 14, copper: 10, silicon: 6 }
  },
  [STRUCTURE_TYPES.ELECTRONICS_BENCH]: {
    id: STRUCTURE_TYPES.ELECTRONICS_BENCH,
    name: 'Atelier électronique',
    description: 'Produit wafers, transistors et circuits.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    machineType: 'electronics_bench',
    energyUse: 7,
    color: '#313f5a',
    borderColor: '#8bb8ff',
    cost: { aluminiumOre: 12, copper: 12, silicon: 8 }
  },
  [STRUCTURE_TYPES.INDUSTRIAL_PRESS]: {
    id: STRUCTURE_TYPES.INDUSTRIAL_PRESS,
    name: 'Presse industrielle',
    description: 'Assemble plaques et composants mécaniques.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    machineType: 'industrial_press',
    energyUse: 10,
    color: '#3e4653',
    borderColor: '#b6c8dc',
    cost: { steelPlate: 5, copper: 8, aluminiumOre: 8 }
  }
,
  [STRUCTURE_TYPES.CONVEYOR]: {
    id: STRUCTURE_TYPES.CONVEYOR,
    name: 'Convoyeur',
    description: 'Transporte automatiquement les ressources dans son sens.',
    radius: 32,
    tilesX: 1,
    tilesY: 1,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    rotatable: true,
    storageKind: 'conveyor',
    storageCapacity: 1,
    automationKind: 'conveyor',
    automationIntervalMs: 720,
    automationOutputs: ['front'],
    color: '#253f4a',
    borderColor: '#6ed7ff',
    cost: { ironOre: 6, copper: 2 }
  },
  [STRUCTURE_TYPES.FAST_CONVEYOR]: {
    id: STRUCTURE_TYPES.FAST_CONVEYOR,
    name: 'Convoyeur rapide',
    description: 'Convoyeur industriel plus rapide.',
    radius: 32,
    tilesX: 1,
    tilesY: 1,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    rotatable: true,
    storageKind: 'conveyor',
    storageCapacity: 1,
    automationKind: 'conveyor',
    automationIntervalMs: 420,
    automationOutputs: ['front'],
    color: '#213f57',
    borderColor: '#79f1ff',
    cost: { ironOre: 8, copper: 4, aluminiumOre: 2 }
  },

  [STRUCTURE_TYPES.SPLITTER]: {
    id: STRUCTURE_TYPES.SPLITTER,
    name: 'Répartiteur',
    description: 'Une entrée, deux sorties.',
    radius: 48,
    tilesX: 1,
    tilesY: 2,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    rotatable: true,
    storageKind: 'conveyor',
    storageCapacity: 1,
    automationKind: 'conveyor',
    automationIntervalMs: 760,
    automationOutputs: ['upper', 'lower'],
    color: '#263f55',
    borderColor: '#a2ebff',
    cost: { ironOre: 10, copper: 5, aluminiumOre: 2 }
  },


  [STRUCTURE_TYPES.MERGER]: {
    id: STRUCTURE_TYPES.MERGER,
    name: 'Fusionneur',
    description: 'Deux entrées, une sortie.',
    radius: 48,
    tilesX: 1,
    tilesY: 2,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    rotatable: true,
    storageKind: 'conveyor',
    storageCapacity: 1,
    automationKind: 'conveyor',
    automationIntervalMs: 700,
    automationOutputs: ['upper'],
    color: '#2a3f50',
    borderColor: '#ffd98a',
    cost: { ironOre: 10, copper: 5, aluminiumOre: 2 }
  },

  [STRUCTURE_TYPES.ROBOT_ARM]: {
    id: STRUCTURE_TYPES.ROBOT_ARM,
    name: 'Bras robotique',
    description: 'Déplace les ressources entre coffre, machine et convoyeur.',
    radius: 32,
    tilesX: 1,
    tilesY: 1,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    rotatable: true,
    automationKind: 'robot_arm',
    automationIntervalMs: 920,
    automationReachTiles: 1,
    color: '#443a2c',
    borderColor: '#ffd27b',
    cost: { ironOre: 8, copper: 4, aluminiumOre: 2 }
  },
  [STRUCTURE_TYPES.FAST_ARM]: {
    id: STRUCTURE_TYPES.FAST_ARM,
    name: 'Bras rapide',
    description: 'Bras robotique à cycle court.',
    radius: 32,
    tilesX: 1,
    tilesY: 1,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    rotatable: true,
    automationKind: 'robot_arm',
    automationIntervalMs: 560,
    automationReachTiles: 1,
    color: '#4d3c25',
    borderColor: '#ffe08a',
    cost: { ironOre: 10, copper: 6, aluminiumOre: 3 }
  },
  [STRUCTURE_TYPES.LONG_ARM]: {
    id: STRUCTURE_TYPES.LONG_ARM,
    name: 'Bras long',
    description: 'Bras robotique capable de franchir deux cases.',
    radius: 32,
    tilesX: 1,
    tilesY: 1,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    rotatable: true,
    automationKind: 'robot_arm',
    automationIntervalMs: 1150,
    automationReachTiles: 2,
    color: '#4b3a2b',
    borderColor: '#ffc86e',
    cost: { ironOre: 12, copper: 6, aluminiumOre: 5 }
  }


};

export function getStructureDef(type) {
  return STRUCTURE_DEFS[String(type || '').toLowerCase()] || null;
}

export function getStructureBuildCost(type) {
  return { ...(getStructureDef(type)?.cost || {}) };
}
