export const BASE_TILE_SIZE = 64;

export const STRUCTURE_TYPES = {
  BASE_CORE: 'base_core',
  OUTPOST_CORE: 'outpost_core',
  LOGISTIC_DRONE_STATION: 'logistic_drone_station',
  LOGISTIC_DRONE_WORKSHOP: 'logistic_drone_workshop',
  LOGISTIC_CHEST_PROVIDER: 'logistic_chest_provider',
  LOGISTIC_CHEST_REQUESTER: 'logistic_chest_requester',
  LOGISTIC_CHEST_BUFFER: 'logistic_chest_buffer',
  WALL: 'wall',
  DOOR: 'door',
  STORAGE: 'storage',
  EQUIPMENT_STORAGE: 'equipment_storage',
  AMMO_STORAGE: 'ammo_storage',
  SOLAR_PANEL: 'solar_panel',
  FUEL_GENERATOR: 'fuel_generator',
  FUEL_TANK: 'fuel_tank',
  FURNACE: 'furnace',
  HIGH_TEMP_FURNACE: 'high_temp_furnace',
  CHEMICAL_REFINERY: 'chemical_refinery',
  ELECTROLYZER: 'electrolyzer',
  ELECTRONICS_BENCH: 'electronics_bench',
  INDUSTRIAL_PRESS: 'industrial_press',
  SCIENCE_LAB: 'science_lab',
  INDUSTRIAL_CONVERTER: 'industrial_converter',
  ROCKET_WORKSHOP: 'rocket_workshop',
  RESEARCH_STATION: 'research_station',
  EQUIPMENT_FABRICATOR: 'equipment_fabricator',
  EQUIPMENT_RD_STATION: 'equipment_rd_station',
  RESOURCE_DEPOSIT: 'resource_deposit',
  MINING_EXTRACTOR: 'mining_extractor',
  CONVEYOR: 'conveyor',
  FAST_CONVEYOR: 'fast_conveyor',
  SPLITTER: 'splitter',
  MERGER: 'merger',
  ROBOT_ARM: 'robot_arm',
  FAST_ARM: 'fast_arm',
  LONG_ARM: 'long_arm',
  DEFENSE_TURRET: 'defense_turret',
  FOUNDATION_METAL: 'foundation_metal',
  FOUNDATION_REINFORCED: 'foundation_reinforced',
  INDUSTRIAL_PLATFORM: 'industrial_platform',
  FOUNDATION_RAMP: 'foundation_ramp',
  TECHNICAL_FLOOR: 'technical_floor',
  RESOURCE_SCANNER: 'resource_scanner',
  BASE_RADAR: 'base_radar',
  ADVANCED_LAB: 'advanced_lab',
  BIOLOGY_LAB: 'biology_lab',
  ENERGY_LAB: 'energy_lab',
  SPACE_LAB: 'space_lab',
  ANOMALY_LAB: 'anomaly_lab',
  MECHANICAL_ASSEMBLER: 'mechanical_assembler',
  ELECTRONIC_ASSEMBLER: 'electronic_assembler',
  WEAPON_WORKSHOP: 'weapon_workshop',
  MODULE_STATION: 'module_station',
  KINETIC_TURRET: 'kinetic_turret',
  LASER_TURRET: 'laser_turret',
  ANTI_MISSILE: 'anti_missile',
  DEFENSE_MINE: 'defense_mine',
  BASE_SHIELD: 'base_shield',
  ORGANIC_NEST: 'organic_nest',
  EVENT_RIFT: 'event_rift'
};

export const STRUCTURE_DEFS = {
  [STRUCTURE_TYPES.BASE_CORE]: {
    id: STRUCTURE_TYPES.BASE_CORE,
    name: 'Noyau de base',
    description: 'Définit une zone de construction personnelle tier 1.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 1200,
    solid: false,
    claimRadius: BASE_TILE_SIZE * 8,
    maxPerOwner: 1,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    color: '#244e68',
    borderColor: '#8de7ff',
    cost: { scrap: 20, ironOre: 12, copper: 6 }
  },
  [STRUCTURE_TYPES.OUTPOST_CORE]: {
    id: STRUCTURE_TYPES.OUTPOST_CORE,
    name: 'Noyau d’avant-poste',
    description: 'Petit noyau 1 × 1 pour exploiter un gisement dans un secteur distant.',
    radius: 32,
    tilesX: 1,
    tilesY: 1,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE,
    maxHp: 360,
    solid: false,
    claimRadius: BASE_TILE_SIZE * 2.5,
    maxPerOwnerPerSector: 4,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    color: '#244d49',
    borderColor: '#8af6d3',
    cost: { steelPlate: 3, copperWire: 4, controlCircuit: 1 }
  },

  [STRUCTURE_TYPES.FOUNDATION_METAL]: {
    id: STRUCTURE_TYPES.FOUNDATION_METAL,
    name: 'Dalle métallique',
    description: 'Sol industriel 1 × 1 aligné sur la grille.',
    radius: 32, tilesX: 1, tilesY: 1, w: BASE_TILE_SIZE, h: BASE_TILE_SIZE,
    maxHp: 0, damageable: false, solid: false, foundation: true,
    buildRange: 1100, gridSize: BASE_TILE_SIZE,
    color: '#263441', borderColor: '#6588a4',
    cost: { ironIngot: 1 }
  },
  [STRUCTURE_TYPES.FOUNDATION_REINFORCED]: {
    id: STRUCTURE_TYPES.FOUNDATION_REINFORCED,
    name: 'Dalle renforcée',
    description: 'Fondation blindée 2 × 2.',
    radius: 64, tilesX: 2, tilesY: 2, w: BASE_TILE_SIZE * 2, h: BASE_TILE_SIZE * 2,
    maxHp: 0, damageable: false, solid: false, foundation: true,
    buildRange: 1100, gridSize: BASE_TILE_SIZE,
    color: '#303b46', borderColor: '#91a9bd',
    cost: { steelPlate: 2, ironIngot: 2 }
  },
  [STRUCTURE_TYPES.INDUSTRIAL_PLATFORM]: {
    id: STRUCTURE_TYPES.INDUSTRIAL_PLATFORM,
    name: 'Plateforme industrielle',
    description: 'Grande plateforme 3 × 3 pour organiser une chaîne de production.',
    radius: 96, tilesX: 3, tilesY: 3, w: BASE_TILE_SIZE * 3, h: BASE_TILE_SIZE * 3,
    maxHp: 0, damageable: false, solid: false, foundation: true,
    buildRange: 1100, gridSize: BASE_TILE_SIZE,
    color: '#2f3a42', borderColor: '#b0c2ce',
    cost: { steelPlate: 4, ironIngot: 4 }
  },
  [STRUCTURE_TYPES.FOUNDATION_RAMP]: {
    id: STRUCTURE_TYPES.FOUNDATION_RAMP,
    name: 'Rampe industrielle',
    description: 'Passage visuel 2 × 1 non bloquant.',
    radius: 48, tilesX: 2, tilesY: 1, w: BASE_TILE_SIZE * 2, h: BASE_TILE_SIZE,
    maxHp: 0, damageable: false, solid: false, foundation: true, rotatable: true,
    buildRange: 1100, gridSize: BASE_TILE_SIZE,
    color: '#33414b', borderColor: '#92aab9',
    cost: { ironIngot: 2 }
  },
  [STRUCTURE_TYPES.TECHNICAL_FLOOR]: {
    id: STRUCTURE_TYPES.TECHNICAL_FLOOR,
    name: 'Sol technique',
    description: 'Dalle 1 × 1 marquant les réseaux techniques.',
    radius: 32, tilesX: 1, tilesY: 1, w: BASE_TILE_SIZE, h: BASE_TILE_SIZE,
    maxHp: 0, damageable: false, solid: false, foundation: true,
    buildRange: 1100, gridSize: BASE_TILE_SIZE,
    color: '#273943', borderColor: '#68bdd5',
    cost: { ironIngot: 1, copperWire: 1 }
  },

  [STRUCTURE_TYPES.LOGISTIC_DRONE_STATION]: {
    id: STRUCTURE_TYPES.LOGISTIC_DRONE_STATION,
    name: 'Station de drones logistiques',
    description: 'Stocke et recharge les drones logistiques. Portée réseau : secteur actuel + 8 secteurs adjacents.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 520,
    damageable: true,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    storageKind: 'resources',
    storageSlots: 1,
    storageCapacity: 80,
    droneStation: true,
    droneCapacity: 8,
    droneRangeSectors: 1,
    droneRechargeSeconds: 20,
    energyUse: 20,
    color: '#26384b',
    borderColor: '#7fdcff',
    cost: { steelPlate: 12, controlCircuit: 3, lithiumBattery: 4, copperWire: 16, servomotor: 2 }
  },

  [STRUCTURE_TYPES.LOGISTIC_DRONE_WORKSHOP]: {
    id: STRUCTURE_TYPES.LOGISTIC_DRONE_WORKSHOP,
    name: 'Atelier de drones logistiques',
    description: 'Assemble des drones logistiques basiques à insérer dans les stations de drones.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    machineType: 'logistic_drone_workshop',
    energyUse: 12,
    color: '#28354f',
    borderColor: '#9ee7ff',
    cost: { steelPlate: 8, copperWire: 10, controlCircuit: 2, lithiumBattery: 2, servomotor: 1 }
  },

  [STRUCTURE_TYPES.LOGISTIC_CHEST_PROVIDER]: {
    id: STRUCTURE_TYPES.LOGISTIC_CHEST_PROVIDER,
    name: 'Coffre de chargement',
    description: 'Coffre fournisseur : les drones prendront ici les ressources à livrer.',
    radius: 32,
    tilesX: 1,
    tilesY: 1,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE,
    maxHp: 260,
    damageable: true,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    storageKind: 'resources',
    storageSlots: 8,
    storageCapacity: 140,
    logisticChest: 'provider',
    color: '#334e3f',
    borderColor: '#8df7b4',
    cost: { steelPlate: 3, copperWire: 2, controlCircuit: 1 }
  },

  [STRUCTURE_TYPES.LOGISTIC_CHEST_REQUESTER]: {
    id: STRUCTURE_TYPES.LOGISTIC_CHEST_REQUESTER,
    name: 'Coffre demandeur',
    description: 'Coffre demandeur : il recevra les ressources demandées par le réseau de drones.',
    radius: 32,
    tilesX: 1,
    tilesY: 1,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE,
    maxHp: 260,
    damageable: true,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    storageKind: 'resources',
    storageSlots: 8,
    storageCapacity: 140,
    logisticChest: 'requester',
    color: '#37445d',
    borderColor: '#9bc4ff',
    cost: { steelPlate: 3, copperWire: 4, controlCircuit: 1 }
  },

  [STRUCTURE_TYPES.LOGISTIC_CHEST_BUFFER]: {
    id: STRUCTURE_TYPES.LOGISTIC_CHEST_BUFFER,
    name: 'Coffre tampon logistique',
    description: 'Stockage neutre utilisé comme réserve et sécurité du réseau logistique.',
    radius: 32,
    tilesX: 1,
    tilesY: 1,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE,
    maxHp: 300,
    damageable: true,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    storageKind: 'resources',
    storageSlots: 10,
    storageCapacity: 180,
    logisticChest: 'buffer',
    color: '#4d4534',
    borderColor: '#ffe19a',
    cost: { steelPlate: 4, copperWire: 2, controlCircuit: 1 }
  },


  [STRUCTURE_TYPES.DEFENSE_TURRET]: {
    id: STRUCTURE_TYPES.DEFENSE_TURRET,
    name: 'Tourelle lance-roquettes',
    description: 'Tourelle défensive autonome. Tire sur les joueurs ennemis dans son rayon, même hors intrusion de base.',
    radius: 48,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 520,
    damageable: true,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    storageKind: 'ammo',
    ammoCapacity: 80,
    energyUse: 18,
    turret: true,
    turretRange: 820,
    turretCooldownMs: 2400,
    turretProjectileSpeed: 720,
    turretProjectileRadius: 6,
    turretDamage: 28,
    turretSplash: 88,
    turretVisual: 'rocket',
    color: '#3f334f',
    borderColor: '#ffb66e',
    cost: { steelPlate: 10, controlCircuit: 3, copperWire: 8, propellant: 8 }
  },

  [STRUCTURE_TYPES.KINETIC_TURRET]: {
    id: STRUCTURE_TYPES.KINETIC_TURRET,
    name: 'Tourelle cinétique',
    description: 'Défense rapide contre créatures et vaisseaux proches.',
    radius: 40, tilesX: 1, tilesY: 1, w: BASE_TILE_SIZE, h: BASE_TILE_SIZE,
    maxHp: 360, damageable: true, buildRange: 1100, gridSize: BASE_TILE_SIZE,
    solid: false, turret: true, turretWeapon: 'kinetic', turretRange: 560,
    turretCooldownMs: 420, turretProjectileSpeed: 1100, turretProjectileRadius: 3,
    turretDamage: 14, turretSplash: 0, turretVisual: 'kinetic',
    energyUse: 4, color: '#403b35', borderColor: '#ffd083',
    cost: { steelPlate: 6, controlCircuit: 2, copperWire: 4 }
  },
  [STRUCTURE_TYPES.LASER_TURRET]: {
    id: STRUCTURE_TYPES.LASER_TURRET,
    name: 'Tourelle laser',
    description: 'Défense énergétique précise à moyenne portée.',
    radius: 48, tilesX: 2, tilesY: 2, w: BASE_TILE_SIZE * 2, h: BASE_TILE_SIZE * 2,
    maxHp: 440, damageable: true, buildRange: 1100, gridSize: BASE_TILE_SIZE,
    solid: false, turret: true, turretWeapon: 'laser', turretRange: 720,
    turretCooldownMs: 850, turretProjectileSpeed: 1600, turretProjectileRadius: 4,
    turretDamage: 23, turretSplash: 12, turretVisual: 'laser',
    energyUse: 14, color: '#293a4c', borderColor: '#74dcff',
    cost: { steelPlate: 8, controlCircuit: 3, laserLens: 2, copperWire: 8 }
  },
  [STRUCTURE_TYPES.ANTI_MISSILE]: {
    id: STRUCTURE_TYPES.ANTI_MISSILE,
    name: 'Défense anti-missile',
    description: 'Intercepte les projectiles hostiles visant la base.',
    radius: 48, tilesX: 2, tilesY: 2, w: BASE_TILE_SIZE * 2, h: BASE_TILE_SIZE * 2,
    maxHp: 420, damageable: true, buildRange: 1100, gridSize: BASE_TILE_SIZE,
    solid: false, antiMissile: true, turretRange: 680, turretCooldownMs: 950,
    energyUse: 16, color: '#30374c', borderColor: '#b7c8ff',
    cost: { steelPlate: 8, controlCircuit: 4, copperWire: 8 }
  },
  [STRUCTURE_TYPES.DEFENSE_MINE]: {
    id: STRUCTURE_TYPES.DEFENSE_MINE,
    name: 'Mine défensive',
    description: 'Charge de proximité consommable contre une cible hostile.',
    radius: 24, tilesX: 1, tilesY: 1, w: BASE_TILE_SIZE, h: BASE_TILE_SIZE,
    maxHp: 80, damageable: true, buildRange: 1100, gridSize: BASE_TILE_SIZE,
    solid: false, defenseMine: true, mineRange: 115, mineDamage: 90,
    color: '#4a332f', borderColor: '#ff8f78',
    cost: { steelPlate: 1, propellant: 2, controlCircuit: 1 }
  },
  [STRUCTURE_TYPES.BASE_RADAR]: {
    id: STRUCTURE_TYPES.BASE_RADAR,
    name: 'Radar de base',
    description: 'Détecte les signatures, portails et menaces du secteur.',
    radius: 64, tilesX: 2, tilesY: 2, w: BASE_TILE_SIZE * 2, h: BASE_TILE_SIZE * 2,
    maxHp: 360, damageable: true, buildRange: 1100, gridSize: BASE_TILE_SIZE,
    solid: false, radarRange: 2800, industrialSignal: 4, energyUse: 12,
    color: '#26384a', borderColor: '#73d9ff',
    cost: { steelPlate: 6, controlCircuit: 4, copperWire: 10 }
  },
  [STRUCTURE_TYPES.BASE_SHIELD]: {
    id: STRUCTURE_TYPES.BASE_SHIELD,
    name: 'Bouclier de base',
    description: 'Réduit les dégâts subis par les structures proches.',
    radius: 64, tilesX: 2, tilesY: 2, w: BASE_TILE_SIZE * 2, h: BASE_TILE_SIZE * 2,
    maxHp: 520, damageable: true, buildRange: 1100, gridSize: BASE_TILE_SIZE,
    solid: false, shieldRange: 520, shieldReduction: 0.28, energyUse: 32,
    color: '#253653', borderColor: '#8eafff',
    cost: { steelPlate: 12, controlCircuit: 5, lithiumBattery: 6, copperWire: 12 }
  },

  [STRUCTURE_TYPES.RESOURCE_SCANNER]: {
    id: STRUCTURE_TYPES.RESOURCE_SCANNER,
    name: 'Scanner de ressources',
    description: 'Révèle les gisements permanents des secteurs visités.',
    radius: 48, tilesX: 2, tilesY: 2, w: BASE_TILE_SIZE * 2, h: BASE_TILE_SIZE * 2,
    maxHp: 0, damageable: false, buildRange: 1100, gridSize: BASE_TILE_SIZE,
    solid: false, resourceScanner: true, scannerRadiusSectors: 1, energyUse: 10,
    color: '#26434c', borderColor: '#78e1d3',
    cost: { steelPlate: 4, controlCircuit: 3, copperWire: 8 }
  },

  [STRUCTURE_TYPES.WALL]: {
    id: STRUCTURE_TYPES.WALL,
    name: 'Mur métallique',
    description: 'Mur solide 3 × 1.',
    radius: 96,
    tilesX: 3,
    tilesY: 1,
    w: BASE_TILE_SIZE * 3,
    h: BASE_TILE_SIZE,
    maxHp: 760,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: true,
    color: '#263748',
    borderColor: '#73d4ff',
    cost: { scrap: 8, ironOre: 6 }
  },
  [STRUCTURE_TYPES.DOOR]: {
    id: STRUCTURE_TYPES.DOOR,
    name: 'Porte renforcée',
    description: 'Porte 3 × 1 ouvrable par le propriétaire.',
    radius: 96,
    tilesX: 3,
    tilesY: 1,
    w: BASE_TILE_SIZE * 3,
    h: BASE_TILE_SIZE,
    maxHp: 680,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: true,
    openable: true,
    color: '#334454',
    borderColor: '#87d9ff',
    cost: { scrap: 6, ironOre: 8, copper: 3 }
  },
  [STRUCTURE_TYPES.STORAGE]: {
    id: STRUCTURE_TYPES.STORAGE,
    name: 'Coffre de ressources',
    description: 'Stockage local de ressources.',
    radius: 32,
    tilesX: 1,
    tilesY: 1,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    storageKind: 'resources',
    storageSlots: 12,
    storageCapacity: 420,
    color: '#30544b',
    borderColor: '#70f0c5',
    cost: { scrap: 10, ironOre: 8, copper: 4 }
  },
  [STRUCTURE_TYPES.EQUIPMENT_STORAGE]: {
    id: STRUCTURE_TYPES.EQUIPMENT_STORAGE,
    name: 'Coffre d’équipement',
    description: 'Stockage local pour armes, lance-roquettes et modules.',
    radius: 32,
    tilesX: 1,
    tilesY: 1,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    storageKind: 'equipment',
    itemCapacity: 18,
    color: '#30425e',
    borderColor: '#8bb8ff',
    cost: { ironIngot: 4, copperWire: 4, scrap: 8 }
  },
  [STRUCTURE_TYPES.SOLAR_PANEL]: {
    id: STRUCTURE_TYPES.SOLAR_PANEL,
    name: 'Panneau solaire',
    description: 'Produit une énergie faible mais gratuite.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    energyOutput: 8,
    color: '#3f594f',
    borderColor: '#bde992',
    cost: { silicon: 8, copper: 6, ironOre: 6 }
  },
  [STRUCTURE_TYPES.FUEL_GENERATOR]: {
    id: STRUCTURE_TYPES.FUEL_GENERATOR,
    name: 'Générateur thermique',
    description: 'Produit beaucoup d’énergie en consommant du carburant.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    storageKind: 'fuel',
    fuelCapacity: 80,
    energyOutput: 34,
    fuelUsePerSecond: 0.025,
    color: '#5d4632',
    borderColor: '#ffb761',
    cost: { ironIngot: 4, copperWire: 4, steelPlate: 2 }
  },
  [STRUCTURE_TYPES.FUEL_TANK]: {
    id: STRUCTURE_TYPES.FUEL_TANK,
    name: 'Réservoir de carburant',
    description: 'Stocke le carburant de la base.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    storageKind: 'fuel',
    fuelCapacity: 240,
    color: '#5b4932',
    borderColor: '#ffc36f',
    cost: { ironIngot: 4, copperWire: 2, steelPlate: 1 }
  }
,
  [STRUCTURE_TYPES.AMMO_STORAGE]: {
    id: STRUCTURE_TYPES.AMMO_STORAGE,
    name: 'Coffre de roquettes',
    description: 'Stockage local pour munitions de lance-roquettes.',
    radius: 32,
    tilesX: 1,
    tilesY: 1,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    storageKind: 'ammo',
    ammoCapacity: 260,
    color: '#5a4030',
    borderColor: '#ffc16f',
    cost: { steelPlate: 2, copperWire: 4 }
  }
,
  [STRUCTURE_TYPES.FURNACE]: {
    id: STRUCTURE_TYPES.FURNACE,
    name: 'Four basique',
    description: 'Fonte simple des minerais communs.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    machineType: 'furnace',
    energyUse: 4,
    color: '#4a3e35',
    borderColor: '#ffb36b',
    cost: { scrap: 8, ironOre: 12, copper: 3 }
  },
  [STRUCTURE_TYPES.HIGH_TEMP_FURNACE]: {
    id: STRUCTURE_TYPES.HIGH_TEMP_FURNACE,
    name: 'Four haute température',
    description: 'Traitement thermique avancé.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    machineType: 'high_temp_furnace',
    energyUse: 9,
    color: '#503833',
    borderColor: '#ff7d5f',
    cost: { ironIngot: 6, copperIngot: 4, graphite: 6 }
  },
  [STRUCTURE_TYPES.CHEMICAL_REFINERY]: {
    id: STRUCTURE_TYPES.CHEMICAL_REFINERY,
    name: 'Raffinerie chimique',
    description: 'Transforme hydrocarbures et matières organiques.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    machineType: 'chemical_refinery',
    energyUse: 6,
    color: '#3d4d3d',
    borderColor: '#95df89',
    cost: { steelPlate: 2, copperWire: 4, silicon: 4 }
  },
  [STRUCTURE_TYPES.ELECTROLYZER]: {
    id: STRUCTURE_TYPES.ELECTROLYZER,
    name: 'Électrolyseur',
    description: 'Sépare et stabilise les volatils.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    machineType: 'electrolyzer',
    energyUse: 8,
    color: '#344f5a',
    borderColor: '#84ddff',
    cost: { steelPlate: 2, copperWire: 6, silicon: 6 }
  },
  [STRUCTURE_TYPES.ELECTRONICS_BENCH]: {
    id: STRUCTURE_TYPES.ELECTRONICS_BENCH,
    name: 'Atelier électronique',
    description: 'Produit wafers, transistors et circuits.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    machineType: 'electronics_bench',
    energyUse: 7,
    color: '#313f5a',
    borderColor: '#8bb8ff',
    cost: { steelPlate: 3, copperWire: 8, silicon: 10 }
  },
  [STRUCTURE_TYPES.SCIENCE_LAB]: {
    id: STRUCTURE_TYPES.SCIENCE_LAB,
    name: 'Laboratoire scientifique',
    description: 'Fabrique des packs de science à partir de composants industriels.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    machineType: 'science_lab',
    energyUse: 6,
    color: '#25384d',
    borderColor: '#7edcff',
    cost: { ironOre: 16, copper: 8, silicon: 6 }
  },


  [STRUCTURE_TYPES.INDUSTRIAL_CONVERTER]: {
    id: STRUCTURE_TYPES.INDUSTRIAL_CONVERTER,
    name: 'Convertisseur industriel',
    description: 'Convertit des ressources via des recettes achetées dans les stations pirates.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    machineType: 'industrial_converter',
    energyUse: 10,
    color: '#3d3048',
    borderColor: '#ff8ce6',
    cost: { steelPlate: 6, copperWire: 10, controlCircuit: 2, titaniumPlate: 1 }
  },


  [STRUCTURE_TYPES.ROCKET_WORKSHOP]: {
    id: STRUCTURE_TYPES.ROCKET_WORKSHOP,
    name: 'Atelier de roquettes',
    description: 'Produit des lots de roquettes à partir de composants industriels.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    rocketWorkshop: true,
    energyUse: 12,
    color: '#4a3828',
    borderColor: '#ffb85c',
    cost: { steelPlate: 5, propellant: 5, controlCircuit: 1 }
  },

  [STRUCTURE_TYPES.RESEARCH_STATION]: {
    id: STRUCTURE_TYPES.RESEARCH_STATION,
    name: 'Station de recherche',
    description: 'Consomme des packs de science pour débloquer des technologies.',
    radius: 72,
    tilesX: 3,
    tilesY: 2,
    w: BASE_TILE_SIZE * 3,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    researchStation: true,
    energyUse: 8,
    color: '#26304d',
    borderColor: '#b58cff',
    cost: { ironIngot: 4, copper: 10, silicon: 6 }
  },

  [STRUCTURE_TYPES.INDUSTRIAL_PRESS]: {
    id: STRUCTURE_TYPES.INDUSTRIAL_PRESS,
    name: 'Presse industrielle',
    description: 'Assemble plaques et composants mécaniques.',
    radius: 64,
    tilesX: 2,
    tilesY: 2,
    w: BASE_TILE_SIZE * 2,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    machineType: 'industrial_press',
    energyUse: 10,
    color: '#3e4653',
    borderColor: '#b6c8dc',
    cost: { ironIngot: 4, copper: 8, graphite: 4 }
  }
,

[STRUCTURE_TYPES.RESOURCE_DEPOSIT]: {
  id: STRUCTURE_TYPES.RESOURCE_DEPOSIT,
  name: 'Gisement',
  description: 'Source permanente exploitable par extracteur.',
  radius: 58,
  tilesX: 2,
  tilesY: 2,
  w: BASE_TILE_SIZE * 2,
  h: BASE_TILE_SIZE * 2,
  maxHp: 0,
  damageable: false,
  buildRange: 1100,
  gridSize: BASE_TILE_SIZE,
  solid: false,
  neutral: true,
  mineable: true,
  infiniteDeposit: true,
  color: '#334a45',
  borderColor: '#9ef0c7',
  cost: {}
},

[STRUCTURE_TYPES.MINING_EXTRACTOR]: {
  id: STRUCTURE_TYPES.MINING_EXTRACTOR,
  name: 'Extracteur minier',
  description: 'Fore une source permanente. Débit limité par le cycle, le buffer et l’énergie.',
  radius: 48,
  tilesX: 2,
  tilesY: 2,
  w: BASE_TILE_SIZE * 2,
  h: BASE_TILE_SIZE * 2,
  maxHp: 0,
  damageable: false,
  buildRange: 1100,
  gridSize: BASE_TILE_SIZE,
  solid: false,
  rotatable: false,
  storageKind: 'conveyor',
  storageCapacity: 8,
  automationKind: 'extractor',
  extractionIntervalMs: 2200,
  extractionRange: BASE_TILE_SIZE * 2.6,
  extractionYield: 1,
  energyUse: 18,
  color: '#314759',
  borderColor: '#9fdcff',
  cost: { steelPlate: 4, copperWire: 8, controlCircuit: 1 }
},

  [STRUCTURE_TYPES.CONVEYOR]: {
    id: STRUCTURE_TYPES.CONVEYOR,
    name: 'Convoyeur',
    description: 'Tapis de transport directionnel. Les objets avancent visiblement jusqu’au prochain convoyeur.',
    radius: 32,
    tilesX: 1,
    tilesY: 1,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    rotatable: true,
    storageKind: 'conveyor',
    storageCapacity: 1,
    automationKind: 'conveyor',
    automationIntervalMs: 720,
    automationOutputs: ['front'],
    color: '#253f4a',
    borderColor: '#6ed7ff',
    cost: { ironOre: 6, copper: 2 }
  },
  [STRUCTURE_TYPES.FAST_CONVEYOR]: {
    id: STRUCTURE_TYPES.FAST_CONVEYOR,
    name: 'Convoyeur rapide',
    description: 'Convoyeur industriel plus rapide.',
    radius: 32,
    tilesX: 1,
    tilesY: 1,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    rotatable: true,
    storageKind: 'conveyor',
    storageCapacity: 1,
    automationKind: 'conveyor',
    automationIntervalMs: 420,
    automationOutputs: ['front'],
    color: '#213f57',
    borderColor: '#79f1ff',
    cost: { ironIngot: 2, copperWire: 2 }
  },

  [STRUCTURE_TYPES.SPLITTER]: {
    id: STRUCTURE_TYPES.SPLITTER,
    name: 'Répartiteur',
    description: 'Répartit un flux vers deux sorties comme une dérivation industrielle.',
    radius: 48,
    tilesX: 1,
    tilesY: 2,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    rotatable: true,
    storageKind: 'conveyor',
    storageCapacity: 1,
    automationKind: 'conveyor',
    automationIntervalMs: 760,
    automationOutputs: ['upper', 'lower'],
    color: '#263f55',
    borderColor: '#a2ebff',
    cost: { ironIngot: 3, copperWire: 2 }
  },


  [STRUCTURE_TYPES.MERGER]: {
    id: STRUCTURE_TYPES.MERGER,
    name: 'Fusionneur',
    description: 'Fusionne deux lignes logistiques vers une seule sortie.',
    radius: 48,
    tilesX: 1,
    tilesY: 2,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE * 2,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    rotatable: true,
    storageKind: 'conveyor',
    storageCapacity: 1,
    automationKind: 'conveyor',
    automationIntervalMs: 700,
    automationOutputs: ['upper'],
    color: '#2a3f50',
    borderColor: '#ffd98a',
    cost: { ironIngot: 3, copperWire: 2 }
  },

  [STRUCTURE_TYPES.ROBOT_ARM]: {
    id: STRUCTURE_TYPES.ROBOT_ARM,
    name: 'Bras robotique',
    description: 'Saisit réellement les ressources et les dépose entre coffre, machine et convoyeur.',
    radius: 32,
    tilesX: 1,
    tilesY: 1,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    rotatable: true,
    automationKind: 'robot_arm',
    automationIntervalMs: 920,
    automationReachTiles: 1,
    color: '#443a2c',
    borderColor: '#ffd27b',
    cost: { ironIngot: 2, copperWire: 2 }
  },
  [STRUCTURE_TYPES.FAST_ARM]: {
    id: STRUCTURE_TYPES.FAST_ARM,
    name: 'Bras rapide',
    description: 'Bras robotique à cycle court.',
    radius: 32,
    tilesX: 1,
    tilesY: 1,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    rotatable: true,
    automationKind: 'robot_arm',
    automationIntervalMs: 560,
    automationReachTiles: 1,
    color: '#4d3c25',
    borderColor: '#ffe08a',
    cost: { steelPlate: 1, copperWire: 3 }
  },
  [STRUCTURE_TYPES.LONG_ARM]: {
    id: STRUCTURE_TYPES.LONG_ARM,
    name: 'Bras long',
    description: 'Bras robotique capable de franchir deux cases.',
    radius: 32,
    tilesX: 1,
    tilesY: 1,
    w: BASE_TILE_SIZE,
    h: BASE_TILE_SIZE,
    maxHp: 0,
    damageable: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    solid: false,
    rotatable: true,
    automationKind: 'robot_arm',
    automationIntervalMs: 1150,
    automationReachTiles: 2,
    color: '#4b3a2b',
    borderColor: '#ffc86e',
    cost: { steelPlate: 1, copperWire: 3 }
  }
,
  [STRUCTURE_TYPES.EQUIPMENT_FABRICATOR]: {
    id: STRUCTURE_TYPES.EQUIPMENT_FABRICATOR,
    name: 'Atelier d’équipement',
    description: 'Fabrique des armes, boucliers, propulseurs et modules à partir de composants avancés.',
    radius: 64,
    tilesX: 3,
    tilesY: 2,
    w: BASE_TILE_SIZE * 3,
    h: BASE_TILE_SIZE * 2,
    maxHp: 420,
    solid: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    color: '#26324f',
    borderColor: '#b58cff',
    energyUse: 18,
    cost: { steelPlate: 8, microprocessor: 2, controlCircuit: 2, advancedSciencePack: 1 }
  }
,
  [STRUCTURE_TYPES.EQUIPMENT_RD_STATION]: {
    id: STRUCTURE_TYPES.EQUIPMENT_RD_STATION,
    name: 'Station R&D',
    description: 'Améliore un objet neutre avec 1 à 3 sciences pour générer des stats, passifs et tags procéduraux.',
    radius: 64,
    tilesX: 3,
    tilesY: 2,
    w: BASE_TILE_SIZE * 3,
    h: BASE_TILE_SIZE * 2,
    maxHp: 420,
    solid: false,
    buildRange: 1100,
    gridSize: BASE_TILE_SIZE,
    color: '#2e244f',
    borderColor: '#d28cff',
    energyUse: 24,
    cost: { steelPlate: 10, microprocessor: 3, controlCircuit: 3, advancedSciencePack: 2 }
  },

  [STRUCTURE_TYPES.ADVANCED_LAB]: {
    id: STRUCTURE_TYPES.ADVANCED_LAB,
    name: 'Laboratoire avancé',
    description: 'Produit les sciences industrielles et avancées.',
    radius: 64, tilesX: 3, tilesY: 2, w: BASE_TILE_SIZE * 3, h: BASE_TILE_SIZE * 2,
    maxHp: 0, damageable: false, solid: false, buildRange: 1100, gridSize: BASE_TILE_SIZE,
    machineType: 'science_lab', labSpecialization: 'advanced', energyUse: 18,
    color: '#293653', borderColor: '#b6c8ff',
    cost: { steelPlate: 8, microprocessor: 2, controlCircuit: 3 }
  },
  [STRUCTURE_TYPES.BIOLOGY_LAB]: {
    id: STRUCTURE_TYPES.BIOLOGY_LAB,
    name: 'Laboratoire biologique',
    description: 'Traite les sciences biologiques.',
    radius: 64, tilesX: 2, tilesY: 2, w: BASE_TILE_SIZE * 2, h: BASE_TILE_SIZE * 2,
    maxHp: 0, damageable: false, solid: false, buildRange: 1100, gridSize: BASE_TILE_SIZE,
    machineType: 'science_lab', labSpecialization: 'biology', energyUse: 14,
    color: '#29483b', borderColor: '#86e6a1',
    cost: { steelPlate: 5, opticalGlass: 3, controlCircuit: 2 }
  },
  [STRUCTURE_TYPES.ENERGY_LAB]: {
    id: STRUCTURE_TYPES.ENERGY_LAB,
    name: 'Laboratoire énergétique',
    description: 'Produit et analyse les sciences énergétiques.',
    radius: 64, tilesX: 2, tilesY: 2, w: BASE_TILE_SIZE * 2, h: BASE_TILE_SIZE * 2,
    maxHp: 0, damageable: false, solid: false, buildRange: 1100, gridSize: BASE_TILE_SIZE,
    machineType: 'science_lab', labSpecialization: 'energy', energyUse: 18,
    color: '#4c4630', borderColor: '#ffe26f',
    cost: { steelPlate: 6, lithiumBattery: 3, controlCircuit: 2 }
  },
  [STRUCTURE_TYPES.SPACE_LAB]: {
    id: STRUCTURE_TYPES.SPACE_LAB,
    name: 'Laboratoire spatial',
    description: 'Recherche avancée pour les environnements lointains.',
    radius: 64, tilesX: 3, tilesY: 2, w: BASE_TILE_SIZE * 3, h: BASE_TILE_SIZE * 2,
    maxHp: 0, damageable: false, solid: false, buildRange: 1100, gridSize: BASE_TILE_SIZE,
    machineType: 'science_lab', labSpecialization: 'space', energyUse: 26,
    color: '#30334d', borderColor: '#a9b8ff',
    cost: { steelPlate: 10, microprocessor: 3, laserLens: 2 }
  },
  [STRUCTURE_TYPES.ANOMALY_LAB]: {
    id: STRUCTURE_TYPES.ANOMALY_LAB,
    name: 'Laboratoire d’anomalie',
    description: 'Analyse les fragments et matériaux précurseurs.',
    radius: 64, tilesX: 3, tilesY: 3, w: BASE_TILE_SIZE * 3, h: BASE_TILE_SIZE * 3,
    maxHp: 360, damageable: true, solid: false, buildRange: 1100, gridSize: BASE_TILE_SIZE,
    machineType: 'science_lab', labSpecialization: 'anomaly', energyUse: 38,
    color: '#3c2e53', borderColor: '#c597ff',
    cost: { steelPlate: 14, microprocessor: 4, advancedSciencePack: 3 }
  },
  [STRUCTURE_TYPES.MECHANICAL_ASSEMBLER]: {
    id: STRUCTURE_TYPES.MECHANICAL_ASSEMBLER,
    name: 'Assembleur mécanique',
    description: 'Assemble des sous-ensembles mécaniques en continu.',
    radius: 64, tilesX: 3, tilesY: 2, w: BASE_TILE_SIZE * 3, h: BASE_TILE_SIZE * 2,
    maxHp: 0, damageable: false, solid: false, buildRange: 1100, gridSize: BASE_TILE_SIZE,
    machineType: 'mechanical_assembler', energyUse: 16,
    color: '#41443d', borderColor: '#c7d09b',
    cost: { steelPlate: 8, servomotor: 2, controlCircuit: 2 }
  },
  [STRUCTURE_TYPES.ELECTRONIC_ASSEMBLER]: {
    id: STRUCTURE_TYPES.ELECTRONIC_ASSEMBLER,
    name: 'Assembleur électronique',
    description: 'Assemble circuits et composants électroniques avancés.',
    radius: 64, tilesX: 3, tilesY: 2, w: BASE_TILE_SIZE * 3, h: BASE_TILE_SIZE * 2,
    maxHp: 0, damageable: false, solid: false, buildRange: 1100, gridSize: BASE_TILE_SIZE,
    machineType: 'electronic_assembler', energyUse: 20,
    color: '#273f46', borderColor: '#75e4d4',
    cost: { steelPlate: 8, microprocessor: 2, controlCircuit: 3 }
  },
  [STRUCTURE_TYPES.WEAPON_WORKSHOP]: {
    id: STRUCTURE_TYPES.WEAPON_WORKSHOP,
    name: 'Atelier d’armement',
    description: 'Produit des composants de défense et des munitions.',
    radius: 64, tilesX: 3, tilesY: 2, w: BASE_TILE_SIZE * 3, h: BASE_TILE_SIZE * 2,
    maxHp: 360, damageable: true, solid: false, buildRange: 1100, gridSize: BASE_TILE_SIZE,
    machineType: 'weapon_workshop', energyUse: 22,
    color: '#49342f', borderColor: '#ff997f',
    cost: { steelPlate: 10, compositeArmor: 2, controlCircuit: 3 }
  },
  [STRUCTURE_TYPES.MODULE_STATION]: {
    id: STRUCTURE_TYPES.MODULE_STATION,
    name: 'Station de modules',
    description: 'Produit les composants nécessaires aux modules de vaisseau.',
    radius: 64, tilesX: 3, tilesY: 2, w: BASE_TILE_SIZE * 3, h: BASE_TILE_SIZE * 2,
    maxHp: 0, damageable: false, solid: false, buildRange: 1100, gridSize: BASE_TILE_SIZE,
    machineType: 'module_station', energyUse: 24,
    color: '#34324d', borderColor: '#b8a9ff',
    cost: { steelPlate: 10, microprocessor: 3, controlCircuit: 3 }
  },
  [STRUCTURE_TYPES.ORGANIC_NEST]: {
    id: STRUCTURE_TYPES.ORGANIC_NEST,
    name: 'Nid organique',
    description: 'Source hostile attirée par l’activité industrielle.',
    radius: 72, tilesX: 2, tilesY: 2, w: BASE_TILE_SIZE * 2, h: BASE_TILE_SIZE * 2,
    maxHp: 780, damageable: true, solid: false, buildable: false, neutral: true,
    color: '#4c332e', borderColor: '#d97969', cost: {}
  },
  [STRUCTURE_TYPES.EVENT_RIFT]: {
    id: STRUCTURE_TYPES.EVENT_RIFT,
    name: 'Faille instable',
    description: 'Anomalie temporaire libérant des créatures.',
    radius: 82, tilesX: 3, tilesY: 3, w: BASE_TILE_SIZE * 3, h: BASE_TILE_SIZE * 3,
    maxHp: 620, damageable: true, solid: false, buildable: false, neutral: true,
    color: '#3d2d55', borderColor: '#b67cff', cost: {}
  }


};

export function getStructureDef(type) {
  return STRUCTURE_DEFS[String(type || '').toLowerCase()] || null;
}

export function getStructureBuildCost(type) {
  return { ...(getStructureDef(type)?.cost || {}) };
}
