export function createInputState() {
  return {
    msx: 0,
    msy: 0,
    a: false,
    z: false,
    e: false,
    r: false,
    interactTap: false,
    rocketTap: false,
    rightDown: false,
    holdActive: false,
    downX: 0,
    downY: 0,
    clickQueued: false,
    moveWorldQueued: false,
    moveWorldX: 0,
    moveWorldY: 0,
    cameraLocked: false,
    cameraToggleQueued: false,
    suppressRightHoldUntilUp: false,
    targetClickQueued: false,
    targetKind: '',
    targetId: 0,
    inputSeq: 0,
    selectSeq: 0,
    actionSeq: 0,
    actions: []
  };
}
